/* Apptonomia — portal texts (EN).
   Locale-specific file. Loaded unconditionally from index.html;
   script.js picks the active one from App.i18n.
   Same key shape as strings.es.js (1:1 parity). */
window.App = window.App || {};
if (window.App.i18n) {
  App.i18n.register({
    core: {
      skipToContent: 'Skip to content'
    },
    meta: {
      description: 'Gateway to the Apptonomia suite: Calculia, Memofun, Okeymoney, Sinonimia, Teclatlon, Routime and Enroca.'
    },
    home: {
      title: 'Apptonomia',
      tagline: 'What are you going to do now?'
    },
    tags: {
      math: 'Math',
      study: 'Study',
      life: 'Daily life',
      words: 'Words',
      keyboard: 'Keyboard',
      activities: 'Activities',
      chess: 'Chess'
    },
    projects: {
      calculia: 'Calculation and logical reasoning through short, visual activities.',
      memofun: 'Flashcards to learn at your own pace.',
      okeymoney: 'Money and everyday autonomy, step by step.',
      sinonimia: 'Easy-read dictionary with synonyms and pictograms.',
      teclatlon: 'Touch typing with a physical computer keyboard.',
      routime: 'Everyday activities to train mind and skills.',
      enroca: 'Chess, step by step: learn, practice and play with help.'
    },
    legal: {
      pageTitle: 'Data protection',
      tagline: 'No registration. No cookies. No analytics.',
      lead: 'Apptonomia does not ask for your personal data. Everything each application saves lives only on this device. Here we explain, in detail, what we save and why.',
      navResponsible: 'Who processes your data',
      navData: 'What we save',
      navRights: 'Your rights',
      navMinors: 'All ages',
      navContact: 'Changes and contact',
      responsibleTitle: 'Who processes your data',
      responsibleP1a: 'Apptonomia is an initiative of ',
      responsibleP1b: ', an independent studio that develops and maintains the suite. There is no server of our own that receives or stores your data: each application is a set of static pages that run in your browser.',
      responsibleP2a: 'The full source code of each application is public and auditable in its GitHub repository at ',
      responsibleP2Link: 'github.com/thenkdframe',
      responsibleP2b: '. Any question about this page can be raised by opening an issue there.',
      dataTitle: 'What we save and why',
      dataP1: 'Every Apptonomia application works without accounts, cookies or analytics: we don’t know who you are or how you use the suite.',
      dataP2: 'The only thing that gets saved lives in your browser’s localStorage, on your own device, and is never sent to any server. In general, the seven applications save:',
      dataItem1Label: 'Game progress',
      dataItem1Text: 'the stars earned, the levels completed, and — where applicable — decks or goals achieved.',
      dataItem2Label: 'Chosen language',
      dataItem2Text: 'so you don’t have to choose it again every time you open the app.',
      dataItem3Label: 'Accessibility and gameplay settings',
      dataItem3Text: 'text size, theme, focus mode, easy read, and other panel settings.',
      dataP3: 'We never save: name, passwords, failures, time taken, number of attempts, comparisons with other people, or detailed usage histories.',
      dataP4: 'This information is kept until it is deleted, and its only purpose is to stop your progress being lost when you close the application.',
      rightsTitle: 'Your rights and how to exercise them',
      rightsP1: 'Since everything saved lives on your device and not on a server, you have direct control: you can view it, change it or delete it at any time, without asking us.',
      rightsP2: 'Each application has its own "Erase my progress" button in its Settings panel. You can also delete this data by clearing your browser’s site data for each website from its settings.',
      rightsLinkPortal: 'Back to the portal',
      minorsTitle: 'All ages and abilities',
      minorsP1: 'The Apptonomia suite is designed to be used autonomously by anyone, regardless of age or abilities.',
      minorsP2: 'Because none of the applications collect personal data on any server, no guardian consent is needed to process data: there is no processing to authorise. We do recommend the usual supervision a family or professional gives to how any device is used.',
      contactTitle: 'Changes and contact',
      contactP1: 'This page may be updated if the suite changes. The change history is public in each GitHub repository.',
      contactP2: 'Last updated: 30 August 2026.',
      contactP3a: 'For questions about this page, open an issue at ',
      contactP3Link: 'github.com/thenkdframe',
      contactP3b: '.',
      footerPortal: 'Back to the portal'
    },
    about: {
      routeNotice: 'This page is not linked from the portal. The only way here is typing the address.',
      tagline: 'A suite of applications to learn at your own pace.',
      lead1: 'Apptonomia is a ',
      leadStrong: 'suite of six web applications',
      lead2: ' built so people with intellectual disabilities can learn on their own, without pressure and with respect for their privacy.',
      navOrigin: 'The origin',
      navPrinciples: 'The principles',
      navTech: 'How it is built',
      navEnroca: 'Enroca: chess',
      navSiblings: 'The six apps',
      navAuthorship: 'Who makes it',
      navCollaborate: 'How to help',
      originTitle: 'The origin',
      originP1a: 'Apptonomia comes from a question that comes up at the end of every occupational therapy session: ',
      originP1em: 'what happens between one session and the next?',
      originP2: 'A person with an intellectual disability practices with their therapist in a clinic, but afterwards they are on their own at home, at school, or in their free time. We wanted a set of tools that respected that autonomy, gave families peace of mind, and served the therapist as a complement between sessions, not a replacement.',
      originP3: 'This suite is the result: six independent applications (Calculia, Memofun, Okeymoney, Routime, Sinonimia and Teclatlon), all in Plain Language, all accessible, all designed so the person using them can go at their own pace.',
      principlesTitle: 'The principles we won’t compromise on',
      principlesIntro: 'These ideas are written into the code first and the text second. If a decision breaks them, that decision is wrong.',
      principleAutonomyTitle: '🤲 Real autonomy',
      principleAutonomyText: 'The person using the app can use it without a professional beside them. If it needs constant help, something has not been solved well.',
      principleNoPressureTitle: '🚫 No pressure',
      principleNoPressureText: 'No timers, no "game over", no negative scores. Mistakes get encouragement, and retrying is unlimited.',
      principlePrivacyTitle: '🔒 Privacy by default',
      principlePrivacyText: 'No sign-up, no cookies, no analytics, no accounts. All progress is saved only on the person’s own device.',
      principleEasyReadTitle: '📖 Plain Language',
      principleEasyReadText: 'Short sentences, one idea per sentence, everyday vocabulary. Zero jargon in the interface the person using the app sees.',
      principleAccessibilityTitle: '♿ Accessibility for everyone',
      principleAccessibilityText: 'Large buttons, high contrast, audio only when gamification or the activity design requires it, full keyboard navigation, and respect for the system’s reduced-motion setting.',
      principleSoberTechTitle: '🧱 Sober technology',
      principleSoberTechText: 'HTML, CSS and JavaScript, no frameworks. Works offline and can be installed as an app. Open source, in a public repository.',
      techTitle: 'How it is built',
      techIntro1: 'Apptonomia is a ',
      techIntroStrong: 'suite of installable web apps (PWA)',
      techIntro2: ' made up of more than 250 static HTML pages across all apps, with hidden routes for families, professionals and maintenance.',
      techItem1Label: 'No server of its own',
      techItem1Text: 'each app is a set of files served by static hosting. No backend, no databases, no API of its own.',
      techItem2Label: 'Works offline',
      techItem2Text: 'once installed, they open even without an internet connection thanks to each app’s service worker and local cache.',
      techItem3Label: 'Persistence only in',
      techItem3Text: 'progress (stars, completed levels, preferences) lives in the device’s browser. It is never sent anywhere.',
      techItem4Label: 'No frameworks, no build step',
      techItem4Text1: 'classic JavaScript compatible with older browsers and with the',
      techItem4Text2: ' protocol. Built so a junior developer can read and modify an activity without surprises.',
      techItem5Label: 'Open source (MIT license)',
      techItem5Text: 'anyone can read it, audit it and suggest improvements. Product decisions are written down in each repository, not in closed-door presentations.',
      techItem6Label: 'Internationalized from day one',
      techItem6Text: 'every piece of text lives in a file per language. Today the suite is available in Spanish (Spain) and English.',
      techItem7Label: 'External dependencies: none',
      techItem7Text: ', except for downloading the Atkinson Hyperlegible and Nunito typefaces (chosen for their high legibility).',
      enrocaTitle: 'Enroca: step-by-step chess',
      enrocaIntro: 'The newest app in the suite teaches chess with adaptations so each person can progress at their own pace. It follows the same principles as the rest (autonomy, no pressure, cognitive accessibility) and adds two specific blocks: what the game brings, and the adaptation strategies that make it playable for everyone.',
      enrocaBenefitsTitle: '🧠 Key benefits',
      enrocaBenefit1: '<strong>Cognitive development:</strong> it improves memory, attention, logical reasoning and problem-solving skills.',
      enrocaBenefit2: '<strong>Autonomy and self-esteem:</strong> it offers a space for leisure and personal growth where each player advances at their own potential.',
      enrocaAdaptationsTitle: '♿ Adaptation strategies',
      enrocaAdaptation1: '<strong>Visual supports:</strong> boards with high-contrast colours, more intuitive pieces, or graphic schemes that explain how each piece moves.',
      enrocaAdaptation2: '<strong>Rule simplification:</strong> start by reducing the number of pieces or the more complex rules to introduce the game step by step.',
      siblingsTitle: 'The seven apps of the suite',
      siblingsIntro: 'Apptonomia is the gateway to six independent applications, each with its own domain and its own development pace. They all share the same accessibility-first philosophy and the same respect for privacy.',
      siblingCalculiaName: 'Calculia',
      siblingCalculiaText: 'Math and logical reasoning.',
      siblingMemofunName: 'Memofun',
      siblingMemofunText: 'Memory and attention.',
      siblingOkeymoneyName: 'Okeymoney',
      siblingOkeymoneyText: 'Personal finance and everyday autonomy.',
      siblingRoutimeName: 'Routime',
      siblingRoutimeText: 'Daily routines and autonomy.',
      siblingSinonimiaName: 'Sinonimia',
      siblingSinonimiaText: 'Plain-language dictionary.',
      siblingTeclatlonName: 'Teclatlon',
      siblingTeclatlonText: 'Touch-typing with a physical keyboard.',
      siblingEnrocaName: 'Enroca',
      siblingEnrocaText: 'Chess lessons, exercises and supported play.',
      siblingLinkHint: 'Opens in a new tab.',
      authorshipTitle: 'Who makes it',
      authorshipP1a: 'Apptonomia and the seven applications of the suite are an initiative by ',
      authorshipP1b: ', an independent studio working on open projects with social and educational impact.',
      authorshipP2: 'The applications are built with the involvement of people with intellectual disabilities, families, occupational therapists and teachers, who test every change and review the content before it reaches production.',
      authorshipP3: 'The code, the text and the decisions are published openly so anyone or any team can audit them, learn from them, and adapt them to other contexts.',
      collaborateTitle: 'How to help',
      collaborateIntro: 'Apptonomia is an open project. There are ways to help that do not require coding:',
      collaborateItem1Label: 'Try it and share feedback',
      collaborateItem1Text: 'families, professionals and the people who use the apps and report what works and what does not are the key piece of the project. Plain Language mistakes, unfriendly tone and activities that are hard to follow only surface through actual use.',
      collaborateItem2Label: 'Suggest activities or content',
      collaborateItem2Text: 'if a skill is not covered, or is covered in a way that could be improved, new content can be proposed. A professional validates the description before it becomes code.',
      collaborateItem3Label: 'Review content',
      collaborateItem3Text: 'translations, culturally appropriate examples, accessible explanations. The interface the person using the apps sees is in Plain Language, and outside eyes help a lot.',
      collaborateItem4Label: 'Contribute code',
      collaborateItem4Text: 'all six repositories are public. Both small changes (an icon, a translation, a style fix) and large ones (new activities, accessibility, support for more languages) are welcome as long as they respect the project’s principles.',
      collaborateItem5Label: 'Spread the word',
      collaborateItem5Text: 'tell people it exists. Many families, professionals and centers do not know tools like this exist until someone shows it to them.',
      collaborateOutro1: 'All the documentation needed to get started is in the',
      collaborateOutro3: 'and',
      collaborateOutro4: 'files of each repository.',
      footerPortal: 'Back to the portal'
    }
  }, 'en');
}
