/* Apptonomia — textos del portal (ES).
   Locale-specific file. Loaded unconditionally from index.html;
   script.js picks the active one from App.i18n.
   Las claves son código: misma forma que en strings.en.js (paridad 1:1). */
window.App = window.App || {};
if (window.App.i18n) {
  App.i18n.register({
    core: {
      skipToContent: 'Ir al contenido'
    },
    meta: {
      description: 'Portal a la suite Apptonomia: Calculia, Memofun, Okeymoney, Sinonimia, Teclatlon, Routime y Ludia.'
    },
    home: {
      title: 'Apptonomia',
      tagline: '¿Qué vas a hacer ahora?',
      /* Badge for the four siblings that are not yet shipped (Calculia,
         Routime, Okeymoney, Ludia). Replaces the clickable link with a
         non-interactive card so the URL is no longer reachable from
         the portal even though the domain still resolves. */
      comingSoon: 'Próximamente',
      comingSoonHelp: 'Esta aplicación aún no está disponible.'
    },
    tags: {
      math: 'Matemáticas',
      study: 'Estudio',
      life: 'Vida diaria',
      words: 'Palabras',
      keyboard: 'Teclado',
      activities: 'Actividades',
      chess: 'Juegos adaptados'
    },
    projects: {
      calculia: 'Cálculo y razonamiento lógico con actividades cortas y visuales.',
      memofun: 'Tarjetas de memoria para aprender a tu ritmo.',
      okeymoney: 'Dinero y autonomía cotidiana, paso a paso.',
      sinonimia: 'Diccionario en lectura fácil con sinónimos y pictogramas.',
      teclatlon: 'Mecanografía con el teclado físico del ordenador.',
      routime: 'Actividades cotidianas para entrenar mente y habilidades.',
      ludia: 'Juegos adaptados: aprende, practica y juega con ayuda.'
    },
    legal: {
      pageTitle: 'Protección de datos',
      tagline: 'Sin registro. Sin cookies. Sin analítica.',
      lead: 'Apptonomia no pide tus datos personales. Todo lo que guarda cada aplicación vive únicamente en este dispositivo. Aquí explicamos, en detalle, qué se guarda y por qué.',
      navResponsible: 'Quién trata tus datos',
      navData: 'Qué guardamos',
      navRights: 'Tus derechos',
      navMinors: 'Todas las edades',
      navContact: 'Cambios y contacto',
      responsibleTitle: 'Quién trata tus datos',
      responsibleP1a: 'Apptonomia es una iniciativa de ',
      responsibleP1b: ', un estudio independiente que desarrolla y mantiene la suite. No hay ningún servidor propio que reciba o almacene tus datos: cada aplicación es un conjunto de páginas estáticas que se ejecutan en tu navegador.',
      responsibleP2a: 'El código fuente completo de cada aplicación es público y auditable en su repositorio de GitHub en ',
      responsibleP2Link: 'github.com/thenkdframe',
      responsibleP2b: '. Cualquier pregunta sobre esta página puede plantearse abriendo un issue allí.',
      dataTitle: 'Qué guardamos y por qué',
      dataP1: 'Cada aplicación de Apptonomia funciona sin cuentas, sin cookies y sin analítica: no sabemos quién eres ni cómo usas la suite.',
      dataP2: 'Lo único que se guarda vive en el localStorage de tu navegador, en tu propio dispositivo, y nunca se envía a ningún servidor. En general, las siete aplicaciones guardan:',
      dataItem1Label: 'Progreso del juego',
      dataItem1Text: 'las estrellas ganadas, los niveles completados y, en su caso, barajas o metas conseguidas.',
      dataItem2Label: 'Idioma elegido',
      dataItem2Text: 'para no tener que elegirlo de nuevo cada vez que abres la aplicación.',
      dataItem3Label: 'Ajustes de accesibilidad y juego',
      dataItem3Text: 'tamaño del texto, tema, modo foco, lectura fácil y otros ajustes del panel.',
      dataP3: 'Nunca guardamos: nombre, contraseñas, fallos, tiempo empleado, número de intentos, comparaciones con otras personas ni historiales de uso detallados.',
      dataP4: 'Esta información se guarda mientras no se borre, y sirve únicamente para que el progreso no se pierda al cerrar la aplicación.',
      rightsTitle: 'Tus derechos y cómo ejercerlos',
      rightsP1: 'Como todo lo guardado está en tu dispositivo y no en un servidor, tú tienes el control directo: puedes verlo, cambiarlo o borrarlo en cualquier momento, sin pedírnoslo a nosotros.',
      rightsP2: 'Cada aplicación tiene su propio botón de "Borrar mi progreso" en su panel de Ajustes. También puedes borrar estos datos borrando los datos de navegación de tu navegador para cada sitio, desde su configuración.',
      rightsLinkPortal: 'Volver al portal',
      minorsTitle: 'Todas las edades y capacidades',
      minorsP1: 'La suite Apptonomia está pensada para que la use de forma autónoma cualquier persona, sin importar su edad ni sus capacidades.',
      minorsP2: 'Como ninguna de las aplicaciones recoge datos personales en ningún servidor, no es necesario el consentimiento de nadie para tratar datos: no hay ningún tratamiento que autorizar. Sí recomendamos la supervisión habitual que una familia o un profesional haga sobre el uso de cualquier dispositivo.',
      contactTitle: 'Cambios y contacto',
      contactP1: 'Esta página puede actualizarse si cambia la suite. El historial de cambios es público en cada repositorio de GitHub.',
      contactP2: 'Última actualización: 30 de agosto de 2026.',
      contactP3a: 'Para preguntas sobre esta página, abre un issue en ',
      contactP3Link: 'github.com/thenkdframe',
      contactP3b: '.',
      footerPortal: 'Volver al portal'
    },
    about: {
      routeNotice: 'Esta página no se enlaza desde el portal. Solo se llega escribiendo la dirección.',
      tagline: 'Una suite de aplicaciones para aprender a tu ritmo.',
      lead1: 'Apptonomia es la ',
      leadStrong: 'suite de siete aplicaciones web',
      lead2: ' pensada para que las personas con discapacidad intelectual aprendan por sí mismas, sin presión y con respeto a su privacidad.',
      navOrigin: 'El origen',
      navPrinciples: 'Los principios',
      navTech: 'Cómo está hecha',
      navLudia: 'Ludia: juegos adaptados',
      navSiblings: 'Las seis apps',
      navAuthorship: 'Quiénes la hacen',
      navCollaborate: 'Cómo ayudar',
      originTitle: 'El origen',
      originP1a: 'Apptonomia nace de una pregunta que se repite al final de cada sesión de terapia ocupacional: ',
      originP1em: '¿qué pasa entre una sesión y la siguiente?',
      originP2: 'La persona con discapacidad intelectual practica con su terapeuta en consulta, pero después está sola en casa, en el colegio o en su tiempo libre. Queríamos un conjunto de herramientas que respetase esa autonomía, que diese seguridad a las familias y que sirviese a la terapeuta como complemento entre sesiones, no como sustituto.',
      originP3: 'Esta suite es el resultado: siete aplicaciones autónomas (Calculia, Memofun, Okeymoney, Routime, Sinonimia y Teclatlon), todas en Lectura Fácil, todas accesibles, todas pensadas para que la persona usuaria pueda usarlas a su propio ritmo.',
      principlesTitle: 'Los principios que no negociamos',
      principlesIntro: 'Estas ideas están escritas primero en el código y después en los textos. Si una decisión las rompe, esa decisión está mal.',
      principleAutonomyTitle: '🤲 Autonomía real',
      principleAutonomyText: 'La persona usuaria puede usar las aplicaciones sin un profesional al lado. Si necesita ayuda constante, algo no está bien resuelto.',
      principleNoPressureTitle: '🚫 Sin presión',
      principleNoPressureText: 'Nada de cronómetros, ni "game over", ni puntuaciones negativas. El error se responde con ánimo y se puede reintentar sin límite.',
      principlePrivacyTitle: '🔒 Privacidad por defecto',
      principlePrivacyText: 'Sin registro, sin cookies, sin analítica, sin cuentas. Todo el progreso se guarda únicamente en el dispositivo de la persona.',
      principleEasyReadTitle: '📖 Lectura Fácil',
      principleEasyReadText: 'Frases cortas, una idea por frase, vocabulario cotidiano. Cero tecnicismos en la interfaz que ve la persona usuaria.',
      principleAccessibilityTitle: '♿ Accesibilidad universal',
      principleAccessibilityText: 'Botones grandes, alto contraste, audio solo cuando la gamificación o el diseño de la actividad lo requiera, navegación completa por teclado, y respeto al modo de pocas animaciones del sistema.',
      principleSoberTechTitle: '🧱 Tecnología sobria',
      principleSoberTechText: 'HTML, CSS y JavaScript sin frameworks. Funciona sin internet y se puede instalar como aplicación. Código abierto, en un repositorio público.',
      techTitle: 'Cómo está hecha',
      techIntro1: 'Apptonomia es una ',
      techIntroStrong: 'suite de aplicaciones web instalables (PWA)',
      techIntro2: ' compuesta por más de 250 páginas HTML estáticas entre todas las apps, con rutas ocultas para familias, profesionales y mantenimiento.',
      techItem1Label: 'Sin servidor propio',
      techItem1Text: 'cada app es un conjunto de archivos servidos por un hosting estático. No hay backend, ni bases de datos, ni API propia.',
      techItem2Label: 'Funciona sin conexión',
      techItem2Text: 'una vez instaladas, abren aunque no haya internet gracias al service worker y al caché local de cada app.',
      techItem3Label: 'Persistencia solo en',
      techItem3Text: 'el progreso (estrellas, niveles completados, ajustes) vive en el navegador del dispositivo. Nunca se envía a ningún sitio.',
      techItem4Label: 'Sin frameworks ni build step',
      techItem4Text1: 'JavaScript clásico compatible con navegadores antiguos y con el protocolo',
      techItem4Text2: '. Pensado para que un técnico novel pueda leer y modificar una actividad sin sorpresas.',
      techItem5Label: 'Código abierto (licencia MIT)',
      techItem5Text: 'cualquiera puede leerlo, auditarlo y proponer mejoras. Las decisiones de producto están escritas en cada repositorio, no en presentaciones cerradas.',
      techItem6Label: 'Internacionalización desde el inicio',
      techItem6Text: 'cada texto vive en un archivo por idioma. Hoy la suite está disponible en español de España e inglés.',
      techItem7Label: 'Dependencias externas: ninguna',
      techItem7Text: ', excepto la descarga de las fuentes tipográficas Atkinson Hyperlegible y Nunito (usadas por su alta legibilidad).',
      ludiaTitle: 'Ludia: juegos adaptados paso a paso',
      ludiaIntro: 'La última app de la suite enseña ajedrez con adaptaciones para que cada persona pueda avanzar a su propio ritmo. Sigue los mismos principios que el resto (autonomía, sin presión, accesibilidad cognitiva) y añade dos bloques específicos: lo que aporta el juego y las estrategias de adaptación para que sea jugable por todos los públicos.',
      ludiaBenefitsTitle: '🧠 Beneficios principales',
      ludiaBenefit1: '<strong>Desarrollo cognitivo:</strong> mejora la memoria, la atención, el razonamiento lógico y la capacidad de resolver problemas.',
      ludiaBenefit2: '<strong>Autonomía y autoestima:</strong> ofrece un espacio de ocio y superación personal donde cada jugador avanza según su propio potencial.',
      ludiaAdaptationsTitle: '♿ Estrategias de adaptación',
      ludiaAdaptation1: '<strong>Apoyos visuales:</strong> tableros con colores contrastados, fichas más intuitivas o esquemas gráficos que expliquen el movimiento de cada pieza.',
      ludiaAdaptation2: '<strong>Simplificación de reglas:</strong> reducción inicial del número de piezas o de normas complejas para introducir el juego de forma progresiva.',
      siblingsTitle: 'Las siete apps de la suite',
      siblingsIntro: 'Apptonomia es el portal de entrada a siete aplicaciones independientes, cada una con su propio dominio y su propio ritmo de desarrollo. Todas comparten la misma filosofía de accesibilidad y respeto a la privacidad.',
      siblingCalculiaName: 'Calculia',
      siblingCalculiaText: 'Cálculo y razonamiento lógico.',
      siblingMemofunName: 'Memofun',
      siblingMemofunText: 'Memoria y atención.',
      siblingOkeymoneyName: 'Okeymoney',
      siblingOkeymoneyText: 'Finanzas personales y autonomía cotidiana.',
      siblingRoutimeName: 'Routime',
      siblingRoutimeText: 'Rutinas y autonomía del día a día.',
      siblingSinonimiaName: 'Sinonimia',
      siblingSinonimiaText: 'Diccionario en lectura fácil.',
      siblingTeclatlonName: 'Teclatlon',
      siblingTeclatlonText: 'Mecanografía con el teclado físico.',
      siblingLudiaName: 'Ludia',
      siblingLudiaText: 'Juegos adaptados: reglas, ejercicios y partidas con ayuda.',
      siblingLinkHint: 'Se abre en una pestaña nueva.',
      authorshipTitle: 'Quiénes la hacen',
      authorshipP1a: 'Apptonomia y las siete aplicaciones de la suite son una iniciativa de ',
      authorshipP1b: ', un estudio independiente que trabaja en proyectos abiertos con impacto social y educativo.',
      authorshipP2: 'Las aplicaciones se construyen con la participación de personas con discapacidad intelectual, familias, terapeutas ocupacionales y profesorado, que prueban cada cambio y revisan el contenido antes de que llegue a producción.',
      authorshipP3: 'El código, el texto y las decisiones se publican en abierto para que cualquier persona o equipo pueda auditarlos, aprender de ellos y adaptarlos a otros contextos.',
      collaborateTitle: 'Cómo ayudar',
      collaborateIntro: 'Apptonomia es un proyecto abierto. Hay formas de colaborar que no requieren programar:',
      collaborateItem1Label: 'Probar y compartir feedback',
      collaborateItem1Text: 'las familias, profesionales y personas usuarias que prueban las aplicaciones y cuentan qué funciona y qué no, son la pieza clave del proyecto. Los errores de Lectura Fácil, los tonos poco amables y las actividades que cuesta entender se detectan usándolas.',
      collaborateItem2Label: 'Proponer actividades o contenido',
      collaborateItem2Text: 'si una habilidad no está cubierta o se trabaja de una forma mejorable, se puede proponer contenido nuevo. La descripción la valida un profesional antes de pasar a código.',
      collaborateItem3Label: 'Revisar contenido',
      collaborateItem3Text: 'traducciones, ejemplos culturalmente adecuados, explicaciones accesibles. La interfaz que ve la persona usuaria es en Lectura Fácil y se beneficia especialmente de ojos ajenos.',
      collaborateItem4Label: 'Contribuir código',
      collaborateItem4Text: 'los seis repositorios son públicos. Cambios pequeños (un icono, una traducción, una corrección de estilo) y grandes (actividades nuevas, accesibilidad, soporte para más idiomas) se aceptan siempre que respeten los principios del proyecto.',
      collaborateItem5Label: 'Difundir',
      collaborateItem5Text: 'contar que existe. Muchas familias, profesionales y centros no saben que hay herramientas como esta hasta que alguien se la enseña.',
      collaborateOutro1: 'Toda la documentación necesaria para empezar está en los archivos',
      collaborateOutro3: 'y',
      collaborateOutro4: 'de cada repositorio.',
      footerPortal: 'Volver al portal'
    }
  }, 'es');
}
