/* 27 non-graphic preventive simulations, grouped into three topics. */
var DATA = {
  es: {
    porRonda: 5,
    niveles: [
      {
        id: 'manipulacion', nombre: 'Manipulación y engaños', descripcion: '9 casos', estrellas: 1,
        casos: [
          { picto: '🎭', situacion: 'Un perfil dice tener tu edad. Te pide que no cuentes a nadie que habláis.', opciones: ['Corto la conversación y se lo cuento a una persona adulta', 'Guardo el secreto para no perder su amistad', 'Le cuento más secretos míos'], correcta: 0, pista: 'Una amistad segura no te obliga a guardar secretos.', explicacion: 'Pedir secretos es una señal de manipulación. Esa persona puede no ser quien dice. Para, bloquea y pide ayuda.' },
          { picto: '🎁', situacion: 'Una persona te manda regalos en un juego. Después te pide una foto íntima.', opciones: ['No la envío. Guardo los mensajes y pido ayuda', 'La envío porque me hizo regalos', 'Le pido otro regalo primero'], correcta: 0, pista: 'Un regalo no compra tu intimidad.', explicacion: 'Nadie puede cobrarte un regalo con una foto. Eso es manipulación. No debes nada a esa persona.' },
          { picto: '💞', situacion: 'Alguien dice: “Si me quisieras, harías una videollamada sin ropa”.', opciones: ['Digo que no, corto el contacto y pido ayuda', 'Acepto para demostrar cariño', 'Acepto solo unos segundos'], correcta: 0, pista: 'El cariño respeta siempre un no.', explicacion: 'Presionar usando el cariño no es amor. Una llamada puede grabarse sin que lo sepas.' },
          { picto: '🧍', situacion: 'Una amistad de internet critica a tu familia y quiere que solo confíes en ella.', opciones: ['Se lo cuento a una persona adulta de confianza', 'Dejo de hablar con mi familia', 'Hago todo lo que me pide'], correcta: 0, pista: 'Aislarte de quienes te ayudan es una señal de peligro.', explicacion: 'Separarte de tu apoyo facilita la manipulación. Habla con alguien de confianza y bloquea el perfil.' },
          { picto: '📹', situacion: 'Una persona adulta te pide una videollamada privada de contenido sexual.', opciones: ['No acepto. Guardo el usuario y aviso a una persona adulta', 'Acepto porque parece amable', 'Acepto con la cara tapada'], correcta: 0, pista: 'Una persona adulta no debe pedir esto a un menor.', explicacion: 'La petición es peligrosa y puede ser delito. No sigas la conversación. Una persona adulta de confianza puede ayudarte a denunciar.' },
          { picto: '📍', situacion: 'Alguien que habla de sexo te pregunta dónde estudias y cuándo sales.', opciones: ['No doy datos. Bloqueo y lo cuento', 'Doy solo el nombre del centro', 'Digo a qué hora salgo'], correcta: 0, pista: 'Tu centro y tus horarios permiten localizarte.', explicacion: 'Mezclar preguntas sexuales con datos de ubicación es una señal grave. Protege tus datos y pide ayuda.' },
          { picto: '🚪', situacion: 'Una persona conocida en redes quiere verte a solas y te pide que mientas sobre dónde vas.', opciones: ['No voy y se lo cuento a una persona adulta', 'Voy porque ya llevamos tiempo hablando', 'Voy y apago la ubicación del móvil'], correcta: 0, pista: 'Pedirte que mientas aumenta el peligro.', explicacion: 'No quedes a solas con alguien conocido solo por internet. El tiempo hablando no demuestra su identidad.' },
          { picto: '🔑', situacion: 'Tu pareja pide tu contraseña para comprobar que no hablas con otras personas.', opciones: ['No la doy. Pongo un límite y pido apoyo si insiste', 'La doy para evitar una discusión', 'La doy y después la cambio'], correcta: 0, pista: 'La confianza no exige entregar contraseñas.', explicacion: 'Controlar tus cuentas es una forma de abuso. Tu contraseña es privada, también dentro de una relación.' },
          { picto: '🫥', situacion: 'Un perfil nuevo conoce cosas tuyas y dice que te vigila. Te pide obedecer.', opciones: ['Guardo capturas, no respondo y pido ayuda', 'Obedezco para que pare', 'Le amenazo también'], correcta: 0, pista: 'No tienes que enfrentarte a una amenaza a solas.', explicacion: 'Guarda mensajes, usuario y fechas. No negocies. Una persona adulta puede ayudarte a bloquear, reportar o denunciar.' }
        ]
      },
      {
        id: 'intimidad', nombre: 'Sexo, imágenes y pornografía', descripcion: '9 casos', estrellas: 1,
        casos: [
          { picto: '📷', situacion: 'Alguien te pide una foto íntima y promete borrarla después.', opciones: ['No la envío y pido ayuda si insiste', 'La envío porque promete borrarla', 'La envío con mensajes que desaparecen'], correcta: 0, pista: 'Una imagen puede copiarse antes de desaparecer.', explicacion: 'No puedes controlar una imagen después de enviarla. Las capturas y grabaciones siguen siendo posibles.' },
          { picto: '🚫', situacion: 'Recibes sin pedirlo una imagen sexual de una persona adulta.', opciones: ['No respondo ni la reenvío. Bloqueo y lo cuento', 'La reenvío al grupo para avisar', 'Mando otra imagen'], correcta: 0, pista: 'Reenviar aumenta el daño.', explicacion: 'No tienes la culpa de recibirla. No la compartas. Una persona adulta puede ayudarte a reportar el perfil.' },
          { picto: '🧒', situacion: 'En un grupo aparece una imagen íntima de una persona menor.', opciones: ['No la guardo ni la reenvío. Aviso de inmediato', 'La guardo como curiosidad', 'La reenvío solo a una amistad'], correcta: 0, pista: 'La imagen muestra a una persona menor y debe dejar de circular.', explicacion: 'Guardar o difundir contenido sexual de menores puede tener consecuencias legales graves. Avisa a una persona adulta o autoridad.' },
          { picto: '🧠', situacion: 'Una amistad dice que ver pornografía enseña cómo son las relaciones reales.', opciones: ['No lo tomo como educación y hablo con una persona adulta de confianza', 'Copio todo lo que aparece', 'Creo que siempre muestra consentimiento'], correcta: 0, pista: 'La pornografía es ficción para personas adultas.', explicacion: 'No enseña relaciones seguras ni consentimiento real. Puede mostrar conductas dañinas como si fueran normales.' },
          { picto: '🔞', situacion: 'Un enlace promete pornografía gratis y pide instalar una aplicación.', opciones: ['No abro el enlace ni instalo nada', 'Instalo la aplicación', 'Doy permiso a la cámara'], correcta: 0, pista: 'Un enlace sexual también puede ser una trampa digital.', explicacion: 'Puede contener malware, robar datos o activar permisos. Cierra el enlace y pide ayuda si ya lo abriste.' },
          { picto: '🪞', situacion: 'En un grupo se burlan de tu cuerpo y dicen que mandes una foto para demostrar algo.', opciones: ['No envío nada. Salgo del grupo y pido apoyo', 'Mando la foto para que paren', 'Insulto el cuerpo de otra persona'], correcta: 0, pista: 'No tienes que demostrar nada con tu cuerpo.', explicacion: 'La vergüenza y la presión de grupo se usan para manipular. Tu cuerpo y tu intimidad te pertenecen.' },
          { picto: '🎥', situacion: 'Durante una videollamada íntima, la otra persona dice que no está grabando.', opciones: ['No hago la llamada: no puedo controlar una grabación', 'Confío porque veo su cara', 'Acepto si también lo hace'], correcta: 0, pista: 'Una pantalla siempre puede grabarse desde otro dispositivo.', explicacion: 'Ver la cara de alguien no evita capturas o grabaciones. Una promesa no elimina el riesgo.' },
          { picto: '🤖', situacion: 'Alguien crea con inteligencia artificial una imagen sexual falsa con tu cara.', opciones: ['Guardo pruebas, lo cuento y pido que se retire', 'Pago para que la borren', 'Creo otra imagen para vengarme'], correcta: 0, pista: 'Que sea falsa no significa que debas soportarla.', explicacion: 'Un montaje sexual puede causar daño y vulnerar tus derechos. No pagues ni negocies. Pide ayuda para reportarlo y retirarlo.' },
          { picto: '💬', situacion: 'Una persona adulta empieza a hacerte preguntas sexuales muy personales.', opciones: ['Dejo de responder, bloqueo y lo cuento', 'Respondo para parecer mayor', 'Le hago preguntas iguales'], correcta: 0, pista: 'Una persona adulta debe respetar los límites de un menor.', explicacion: 'Es una conducta inadecuada y peligrosa. No has provocado la situación. Guarda el perfil y pide ayuda.' }
        ]
      },
      {
        id: 'ley', nombre: 'Amenazas, ayuda y consecuencias', descripcion: '9 casos', estrellas: 1,
        casos: [
          { picto: '⚠️', situacion: 'Alguien amenaza con publicar una foto íntima si no mandas más.', opciones: ['No mando más. Guardo las amenazas y pido ayuda', 'Mando otra para ganar tiempo', 'Pago sin contárselo a nadie'], correcta: 0, pista: 'Ceder suele hacer que las amenazas continúen.', explicacion: 'Esto es chantaje sexual. Corta el contacto y guarda pruebas. No es tu culpa, aunque enviaras la primera imagen.' },
          { picto: '💳', situacion: 'Te exigen dinero para no difundir un montaje sexual.', opciones: ['No pago. Guardo pruebas y aviso', 'Pago una vez', 'Doy mis datos bancarios'], correcta: 0, pista: 'Pagar no garantiza que pare el chantaje.', explicacion: 'No negocies ni pagues. Guarda usuario, mensajes y fechas. Pide ayuda para reportar o denunciar.' },
          { picto: '📲', situacion: 'Te llega una imagen íntima de un menor y quieres denunciarla.', opciones: ['No la reenvío. Enseño el mensaje directamente a una persona adulta', 'La reenvío como prueba a muchas personas', 'La publico para encontrar a la víctima'], correcta: 0, pista: 'La prueba puede mostrarse sin crear nuevas copias.', explicacion: 'No difundas el archivo. Conserva el mensaje solo para que una persona adulta o autoridad indique cómo actuar.' },
          { picto: '🗑️', situacion: 'Una imagen íntima tuya circula sin permiso. Te da vergüenza pedir ayuda.', opciones: ['Lo cuento: pueden ayudarme a retirarla y detener la difusión', 'Borro mi cuenta y no digo nada', 'Acepto que ya no hay solución'], correcta: 0, pista: 'La vergüenza pertenece a quien comparte sin permiso, no a la víctima.', explicacion: 'Difundir imágenes íntimas sin permiso puede ser delito. Hay canales de retirada y ayuda. Actuar pronto puede frenar el daño.' },
          { picto: '⚖️', situacion: 'Una amistad recibió una foto íntima con permiso. Ahora quiere publicarla tras una ruptura.', opciones: ['Le digo que no la publique y aviso a una persona adulta', 'Le digo que tiene derecho porque se la enviaron', 'La comparto también'], correcta: 0, pista: 'Recibir una imagen no da permiso para difundirla.', explicacion: 'Compartir una imagen íntima sin consentimiento puede ser delito, aunque se recibiera con permiso.' },
          { picto: '👥', situacion: 'En el grupo dicen que reenviar una foto íntima de un menor “solo una vez” no importa.', opciones: ['No la reenvío y aviso para frenar la cadena', 'La reenvío una vez', 'La guardo para verla después'], correcta: 0, pista: 'Cada reenvío crea otra copia y aumenta el daño.', explicacion: 'Poseer o difundir contenido sexual de menores puede tener consecuencias legales. Una sola copia también importa.' },
          { picto: '🕵️', situacion: 'Un adulto se hizo pasar por menor y consiguió imágenes íntimas.', opciones: ['Lo cuento y guardo los mensajes para pedir ayuda', 'Borro todo antes de contarlo', 'Sigo hablando para descubrir quién es'], correcta: 0, pista: 'No investigues por tu cuenta a una persona peligrosa.', explicacion: 'Engañar a un menor con fines sexuales es una conducta grave. Guarda las pruebas y deja que personas adultas y autoridades actúen.' },
          { picto: '✅', situacion: 'Una persona aceptó una foto normal, pero no que la conviertan en un montaje sexual.', opciones: ['Respeto su decisión y no creo ni comparto el montaje', 'Lo hago porque la foto era pública', 'Lo comparto si no digo su nombre'], correcta: 0, pista: 'Una foto pública no elimina el consentimiento.', explicacion: 'Crear o difundir un montaje sexual puede vulnerar la intimidad y causar daño grave. Siempre se necesita respeto y consentimiento.' },
          { picto: '🛟', situacion: 'No sabes si una situación sexual en redes es delito, pero te hace sentir miedo.', opciones: ['Paro y se lo cuento a una persona adulta de confianza', 'Espero a tener pruebas perfectas', 'Sigo para no exagerar'], correcta: 0, pista: 'No necesitas saber de leyes para pedir ayuda.', explicacion: 'Tu miedo es razón suficiente para parar. Una persona adulta, el centro educativo o servicios especializados pueden orientarte.' }
        ]
      }
    ]
  },
  en: {
    porRonda: 5,
    niveles: [
      {
        id: 'manipulation', nombre: 'Manipulation and deception', descripcion: '9 cases', estrellas: 1,
        casos: [
          { picto: '🎭', situacion: 'A profile says they are your age. They ask you to keep your chats secret.', opciones: ['I stop the chat and tell a trusted adult', 'I keep the secret so I do not lose the friendship', 'I share more secrets'], correcta: 0, pista: 'A safe friendship does not force you to keep secrets.', explicacion: 'Asking for secrecy is a sign of manipulation. The person may not be who they claim. Stop, block and ask for help.' },
          { picto: '🎁', situacion: 'Someone sends you gifts in a game. Then they ask for an intimate image.', opciones: ['I do not send it. I save the messages and ask for help', 'I send it because they gave me gifts', 'I ask for another gift first'], correcta: 0, pista: 'A gift does not buy your privacy.', explicacion: 'Nobody can charge you for a gift with an image. This is manipulation. You owe that person nothing.' },
          { picto: '💞', situacion: 'Someone says, “If you loved me, you would make a video call without clothes.”', opciones: ['I say no, end contact and ask for help', 'I agree to prove I care', 'I agree for a few seconds'], correcta: 0, pista: 'Care always respects no.', explicacion: 'Using affection to pressure you is not love. A call can be recorded without your knowledge.' },
          { picto: '🧍', situacion: 'An online friend criticises your family and wants you to trust only them.', opciones: ['I tell a trusted adult', 'I stop talking to my family', 'I do everything they ask'], correcta: 0, pista: 'Isolating you from support is a danger sign.', explicacion: 'Separating you from support makes manipulation easier. Talk to someone you trust and block the profile.' },
          { picto: '📹', situacion: 'An adult asks you for a private sexual video call.', opciones: ['I refuse. I save the username and tell a trusted adult', 'I agree because they seem kind', 'I agree with my face hidden'], correcta: 0, pista: 'An adult must not ask a minor for this.', explicacion: 'The request is dangerous and may be a crime. End the chat. A trusted adult can help you report it.' },
          { picto: '📍', situacion: 'Someone talking about sex asks where you study and when you leave.', opciones: ['I give no details. I block and tell someone', 'I give only the school name', 'I say when I leave'], correcta: 0, pista: 'Your school and schedule can reveal your location.', explicacion: 'Mixing sexual questions with location details is a serious warning sign. Protect your details and ask for help.' },
          { picto: '🚪', situacion: 'Someone met online wants to see you alone and asks you to lie about where you are going.', opciones: ['I do not go and I tell a trusted adult', 'I go because we have talked for a long time', 'I go and turn off phone location'], correcta: 0, pista: 'Asking you to lie increases the danger.', explicacion: 'Do not meet alone with someone known only online. Time spent chatting does not prove their identity.' },
          { picto: '🔑', situacion: 'Your partner asks for your password to check who you talk to.', opciones: ['I refuse. I set a boundary and seek support if they insist', 'I give it to avoid an argument', 'I give it and change it later'], correcta: 0, pista: 'Trust does not require passwords.', explicacion: 'Controlling your accounts is abusive. Your password is private, including in a relationship.' },
          { picto: '🫥', situacion: 'A new profile knows things about you, says they watch you and demands obedience.', opciones: ['I save screenshots, do not reply and ask for help', 'I obey so they stop', 'I threaten them too'], correcta: 0, pista: 'You do not have to face a threat alone.', explicacion: 'Save messages, username and dates. Do not negotiate. An adult can help you block, report or contact police.' }
        ]
      },
      {
        id: 'intimacy', nombre: 'Sex, images and pornography', descripcion: '9 cases', estrellas: 1,
        casos: [
          { picto: '📷', situacion: 'Someone asks for an intimate image and promises to delete it later.', opciones: ['I do not send it and ask for help if they insist', 'I send it because they promise to delete it', 'I use disappearing messages'], correcta: 0, pista: 'An image can be copied before it disappears.', explicacion: 'You cannot control an image after sending it. Screenshots and recordings are still possible.' },
          { picto: '🚫', situacion: 'An adult sends you a sexual image you did not ask for.', opciones: ['I do not reply or forward it. I block and tell someone', 'I forward it to warn the group', 'I send another image'], correcta: 0, pista: 'Forwarding increases the harm.', explicacion: 'It is not your fault that you received it. Do not share it. An adult can help report the profile.' },
          { picto: '🧒', situacion: 'An intimate image of a minor appears in a group.', opciones: ['I do not save or forward it. I tell an adult immediately', 'I save it out of curiosity', 'I forward it to one friend'], correcta: 0, pista: 'The image shows a minor and must stop circulating.', explicacion: 'Keeping or sharing sexual content involving minors can have serious legal consequences. Tell a trusted adult or authority.' },
          { picto: '🧠', situacion: 'A friend says pornography teaches what real relationships are like.', opciones: ['I do not use it as education and talk to a trusted adult', 'I copy everything shown', 'I believe it always shows consent'], correcta: 0, pista: 'Pornography is fiction made for adults.', explicacion: 'It does not teach safe relationships or real consent. It may show harmful behaviour as normal.' },
          { picto: '🔞', situacion: 'A link promises free pornography and asks you to install an app.', opciones: ['I do not open the link or install anything', 'I install the app', 'I allow camera access'], correcta: 0, pista: 'A sexual link can also be a digital trap.', explicacion: 'It may contain malware, steal information or enable permissions. Close it and ask for help if you opened it.' },
          { picto: '🪞', situacion: 'People mock your body and demand an image to prove something.', opciones: ['I send nothing. I leave the group and seek support', 'I send it so they stop', 'I insult someone else’s body'], correcta: 0, pista: 'You do not have to prove anything with your body.', explicacion: 'Shame and group pressure are used to manipulate. Your body and privacy belong to you.' },
          { picto: '🎥', situacion: 'During an intimate video call, the other person says they are not recording.', opciones: ['I do not make the call because I cannot control recording', 'I trust them because I see their face', 'I agree if they do it too'], correcta: 0, pista: 'A screen can always be recorded by another device.', explicacion: 'Seeing someone’s face does not prevent screenshots or recordings. A promise does not remove the risk.' },
          { picto: '🤖', situacion: 'Someone uses AI to make a fake sexual image with your face.', opciones: ['I save evidence, tell someone and seek removal', 'I pay them to delete it', 'I make another image for revenge'], correcta: 0, pista: 'Being fake does not mean you must tolerate it.', explicacion: 'A sexual fake can cause harm and violate your rights. Do not pay or negotiate. Ask for help reporting and removing it.' },
          { picto: '💬', situacion: 'An adult begins asking very personal sexual questions.', opciones: ['I stop replying, block and tell someone', 'I answer to seem older', 'I ask the same questions'], correcta: 0, pista: 'An adult must respect a minor’s boundaries.', explicacion: 'This is inappropriate and dangerous behaviour. You did not cause it. Save the profile and ask for help.' }
        ]
      },
      {
        id: 'law', nombre: 'Threats, help and consequences', descripcion: '9 cases', estrellas: 1,
        casos: [
          { picto: '⚠️', situacion: 'Someone threatens to post an intimate image unless you send more.', opciones: ['I send no more. I save the threats and ask for help', 'I send another to gain time', 'I pay without telling anyone'], correcta: 0, pista: 'Giving in usually makes threats continue.', explicacion: 'This is sexual blackmail. End contact and save evidence. It is not your fault, even if you sent the first image.' },
          { picto: '💳', situacion: 'Someone demands money not to share a sexual fake.', opciones: ['I do not pay. I save evidence and tell someone', 'I pay once', 'I give my bank details'], correcta: 0, pista: 'Paying does not guarantee the blackmail will stop.', explicacion: 'Do not negotiate or pay. Save the username, messages and dates. Ask for help reporting it.' },
          { picto: '📲', situacion: 'You receive an intimate image of a minor and want to report it.', opciones: ['I do not forward it. I show the message directly to an adult', 'I forward it to many people as evidence', 'I post it to find the victim'], correcta: 0, pista: 'Evidence can be shown without making new copies.', explicacion: 'Do not spread the file. Keep the message only so an adult or authority can tell you what to do.' },
          { picto: '🗑️', situacion: 'An intimate image of you is shared without permission. You feel too ashamed to ask for help.', opciones: ['I tell someone: they can help remove it and stop the spread', 'I delete my account and say nothing', 'I accept that there is no solution'], correcta: 0, pista: 'The shame belongs to the person sharing it, not the victim.', explicacion: 'Sharing intimate images without permission may be a crime. Removal and support services exist. Acting early can limit harm.' },
          { picto: '⚖️', situacion: 'A friend received an intimate image with permission and now wants to post it after a breakup.', opciones: ['I tell them not to post it and alert an adult', 'I say they have a right because it was sent to them', 'I share it too'], correcta: 0, pista: 'Receiving an image does not give permission to share it.', explicacion: 'Sharing an intimate image without consent may be a crime, even when it was received with permission.' },
          { picto: '👥', situacion: 'A group says forwarding an intimate image of a minor “just once” does not matter.', opciones: ['I do not forward it and alert someone to stop the chain', 'I forward it once', 'I save it for later'], correcta: 0, pista: 'Every forward makes another copy and increases harm.', explicacion: 'Possessing or sharing sexual content involving minors can have legal consequences. One copy still matters.' },
          { picto: '🕵️', situacion: 'An adult pretended to be a minor and obtained intimate images.', opciones: ['I tell someone and save the messages for help', 'I delete everything before telling', 'I keep talking to discover who it is'], correcta: 0, pista: 'Do not investigate a dangerous person yourself.', explicacion: 'Deceiving a minor for sexual purposes is serious. Save evidence and let adults and authorities act.' },
          { picto: '✅', situacion: 'Someone agreed to a normal photo, but not to a sexual fake made from it.', opciones: ['I respect their choice and do not create or share it', 'I make it because the photo was public', 'I share it without their name'], correcta: 0, pista: 'A public photo does not remove consent.', explicacion: 'Creating or sharing a sexual fake can violate privacy and cause serious harm. Respect and consent are always required.' },
          { picto: '🛟', situacion: 'You do not know whether a sexual situation online is illegal, but it frightens you.', opciones: ['I stop and tell a trusted adult', 'I wait for perfect evidence', 'I continue so I do not overreact'], correcta: 0, pista: 'You do not need legal knowledge to ask for help.', explicacion: 'Fear is enough reason to stop. A trusted adult, school or specialist service can guide you.' }
        ]
      }
    ]
  }
};
