/* ============================================================
   Apptonomia — Textos de El Monedero / The Coin Purse (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '💶 El Monedero',
      instruccion: 'Aquí practicas dos cosas: contar cuánto dinero hay, y pagar el precio justo.',
      volverMenu: '← Menú',
      elegirNivel: 'Elige el nivel',
      vecesTexto: '{n} veces',
      btnOtroNivel: 'Elegir otro nivel',
      menuContar: '¿Cuánto hay?',
      menuContarDetalle: 'Mira el dinero y elige el total.',
      menuPagar: 'Paga justo',
      menuPagarDetalle: 'Toca el dinero hasta el precio exacto.',
      /* --- Dinero (aria y palabras habladas) --- */
      monedaDe: 'Moneda de {v}',
      billeteDe: 'Billete de {v}',
      anadirDinero: 'Añadir {d}',
      palabraEuro: 'euro',
      palabraEuros: 'euros',
      palabraCentimos: 'céntimos',
      palabraY: 'y',
      ctsCorto: 'cts',
      /* --- ¿Cuánto hay? --- */
      contarPregunta: '¿Cuánto dinero hay?',
      ariaMesa: 'Dinero sobre la mesa',
      pistaContar: 'Cuenta otra vez, despacio. Empieza por el dinero más grande.',
      unaMonedaDe: '1 moneda de {v}',
      variasMonedasDe: '{n} monedas de {v}',
      unBilleteDe: '1 billete de {v}',
      variosBilletesDe: '{n} billetes de {v}',
      explicacionBien: '¡Eso es! Hay {d}. En total, {total}.',
      explicacionCasi: 'Mira: hay {d}. En total, {total}.',
      resumenContar: 'Has contado bien {n} de {t}.',
      /* --- Paga justo --- */
      pagarInstruccion: 'Mira el precio. Toca el dinero hasta llegar al precio justo.',
      hasPuesto: 'Has puesto: {total}',
      quitarUltima: '↩ Quitar última',
      vaciar: '🗑 Vaciar',
      comprobar: 'Comprobar',
      escucharPrecio: 'Escuchar el precio',
      cuesta: '{nombre}: {precio}',
      faltaDinero1: 'Falta dinero. Mira el precio y mira lo que has puesto.',
      sobraDinero1: 'Sobra dinero. Mira el precio y mira lo que has puesto.',
      faltaDinero2: 'Faltan {dif}. Añade más dinero.',
      sobraDinero2: 'Sobran {dif}. Quita algún dinero.',
      resumenPagar: 'Has pagado justo a la primera {n} de {t}.',
      btnAyuda: '💡 Ayuda',
      ariaEscucharAyuda: 'Escuchar la ayuda',
      ayudaPagar1: 'Mira el precio y mira tu total. ¿Cuál es el dinero más grande que cabe sin pasarte?',
      ayudaPagar2: 'Toca el dinero marcado: cabe sin pasarte del precio.',
      ayudaQuita1: 'Mira tu total. ¿Has puesto más dinero que el precio?',
      ayudaQuita2: 'Toca el botón marcado para quitar dinero.',
      ayudaComprobar: 'Tu total es igual al precio. ¡Toca Comprobar!'
    },
    en: {
      title: '💶 The Coin Purse',
      instruccion: 'Here you practise two things: counting how much money there is, and paying the exact price.',
      volverMenu: '← Menu',
      elegirNivel: 'Choose the level',
      vecesTexto: '{n} times',
      btnOtroNivel: 'Choose another level',
      menuContar: 'How much is there?',
      menuContarDetalle: 'Look at the money and choose the total.',
      menuPagar: 'Pay the exact price',
      menuPagarDetalle: 'Touch the money up to the exact price.',
      /* --- Money (aria and spoken words) --- */
      monedaDe: '{v} coin',
      billeteDe: '{v} banknote',
      anadirDinero: 'Add {d}',
      palabraEuro: 'euro',
      palabraEuros: 'euros',
      palabraCentimos: 'cents',
      palabraY: 'and',
      ctsCorto: 'cts',
      /* --- How much is there? --- */
      contarPregunta: 'How much money is there?',
      ariaMesa: 'Money on the table',
      pistaContar: 'Count again, slowly. Start with the biggest money.',
      unaMonedaDe: '1 coin of {v}',
      variasMonedasDe: '{n} coins of {v}',
      unBilleteDe: '1 banknote of {v}',
      variosBilletesDe: '{n} banknotes of {v}',
      explicacionBien: 'That is it! There is {d}. In total, {total}.',
      explicacionCasi: 'Look: there is {d}. In total, {total}.',
      resumenContar: 'You counted correctly {n} out of {t}.',
      /* --- Pay the exact price --- */
      pagarInstruccion: 'Look at the price. Touch the money until you reach the exact price.',
      hasPuesto: 'You have put in: {total}',
      quitarUltima: '↩ Remove last',
      vaciar: '🗑 Empty',
      comprobar: 'Check',
      escucharPrecio: 'Listen to the price',
      cuesta: '{nombre}: {precio}',
      faltaDinero1: 'Not enough money. Look at the price and look at what you have put in.',
      sobraDinero1: 'Too much money. Look at the price and look at what you have put in.',
      faltaDinero2: '{dif} missing. Add more money.',
      sobraDinero2: '{dif} too much. Remove some money.',
      resumenPagar: 'You paid the exact price first time {n} out of {t}.',
      btnAyuda: '💡 Help',
      ariaEscucharAyuda: 'Listen to the help',
      ayudaPagar1: 'Look at the price and look at your total. What is the biggest money that fits without going over?',
      ayudaPagar2: 'Touch the marked money: it fits without going over the price.',
      ayudaQuita1: 'Look at your total. Have you put in more money than the price?',
      ayudaQuita2: 'Touch the marked button to remove money.',
      ayudaComprobar: 'Your total equals the price. Touch Check!'
    }
  });
})();
