/* ============================================================
   Apptonomia — Textos de El Monedero / The Coin Purse (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '💶 El Monedero',
      instruccion: 'Aquí practicas el dinero de verdad: contarlo, pagar, comprobar el cambio y ahorrar.',
      volverMenu: '← Menú',
      elegirNivel: 'Elige el nivel',
      vecesTexto: '{n} veces',
      btnOtroNivel: 'Elegir otro nivel',
      menuContar: '¿Cuánto hay?',
      menuContarDetalle: 'Mira el dinero y elige el total.',
      menuPagar: 'Paga justo',
      menuPagarDetalle: 'Toca el dinero hasta el precio exacto.',
      menuConQuePago: '¿Con qué pago?',
      menuConQuePagoDetalle: 'Elige el dinero que llega.',
      menuCambio: '¿Está bien el cambio?',
      menuCambioDetalle: 'Cuenta el cambio y decide.',
      menuHucha: 'La Hucha',
      menuHuchaDetalle: '¿Cuánto te falta para comprarlo?',
      menuRedondeo: 'Más o menos',
      menuRedondeoDetalle: '¿Cuánto es, sin contar céntimos?',
      instruccionContar: '¿Cuánto dinero hay? Cuenta el dinero y elige el total.',
      instruccionConQuePago: 'No tienes el precio justo. Elige el dinero que llega para pagar.',
      instruccionCambio: 'Has pagado. Cuenta el cambio y decide si está bien.',
      instruccionHucha: 'Quieres comprar algo. Cuenta tu dinero y calcula cuánto te falta.',
      instruccionRedondeo: 'Mira el precio. Di cuánto es, más o menos, sin contar los céntimos.',
      /* (Las palabras del dinero — euro, céntimos, moneda de… —
         viven en el módulo compartido assets/js/dinero.js.) */
      anadirDinero: 'Añadir {d}',
      /* --- ¿Cuánto hay? --- */
      contarPregunta: '¿Cuánto dinero hay?',
      ariaMesa: 'Dinero sobre la mesa',
      pistaContar: 'Cuenta otra vez, despacio. Empieza por el dinero más grande.',
      explicacionBien: '¡Eso es! Hay {d}. En total, {total}.',
      explicacionCasi: 'Mira: hay {d}. En total, {total}.',
      resumenContar: 'Has contado bien {n} de {t}.',
      /* --- ¿Con qué pago? --- */
      enunciadoConQuePago: '{nombre} cuesta {precio}. No tienes el precio justo. ¿Con qué pagas?',
      pistaConQuePago: 'Mira el precio. ¿Ese dinero es más o menos que el precio?',
      explicacionPagoBien: '¡Eso es! Pagas con {pagado}. Te devuelven {cambio}.',
      explicacionPagoCasi: 'Mira: ese dinero es menos que el precio. Se paga con {pagado}. Te devuelven {cambio}.',
      teDevuelven: 'Te devuelven:',
      resumenConQuePago: 'Has pagado bien a la primera {n} de {t}.',
      /* --- ¿Está bien el cambio? --- */
      enunciadoCambio: 'Cuesta {precio}. Pagas con {pagado}. Te devuelven esto. ¿Está bien el cambio?',
      si: 'Sí',
      no: 'No',
      pistaCambio: 'Cuenta el dinero de la mesa. ¿Cuánto te han devuelto?',
      explicacionCambioBien: 'El cambio bueno es {bueno}. Te han devuelto {mostrado}. ¡Está bien!',
      explicacionCambioFalta: 'El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal: te falta dinero.',
      explicacionCambioSobra: 'El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal: te han dado de más.',
      resumenCambio: 'Has comprobado bien {n} de {t}.',
      /* --- La Hucha --- */
      enunciadoHucha: 'Quieres comprar {nombre}. Cuesta {precio}. Tienes este dinero. ¿Cuánto te falta?',
      pistaHucha: 'Cuenta primero el dinero de la mesa. Después mira el precio.',
      explicacionHuchaBien: '¡Eso es! Cuesta {precio}. Tienes {tienes}. Te faltan {falta}.',
      explicacionHuchaCasi: 'Mira: cuesta {precio}. Tienes {tienes}. Te faltan {falta}.',
      resumenHucha: 'Has calculado bien {n} de {t}.',
      /* --- Más o menos --- */
      enunciadoRedondeo: '{nombre} cuesta {precio}. ¿Cuánto es, más o menos?',
      unosEuros: 'unos {n} €',
      pistaRedondeo: 'Mira los céntimos. ¿Están más cerca del euro de arriba o del euro de abajo?',
      explicacionRedondeoBien: '¡Eso es! {precio} está muy cerca de {n} €. Decimos: unos {n} €.',
      explicacionRedondeoCasi: 'Mira: {precio} está muy cerca de {n} €. Decimos: unos {n} €.',
      explicacionRedondeoMedioBien: '¡Eso es! {precio} acaba en 50. Cuando acaba en 50, decimos el euro de arriba: unos {n} €.',
      explicacionRedondeoMedioCasi: 'Mira: {precio} acaba en 50. Cuando acaba en 50, decimos el euro de arriba: unos {n} €.',
      resumenRedondeo: 'Has estimado bien {n} de {t}.',
      /* --- Paga justo --- */
      pagarInstruccion: 'Mira el precio. Toca el dinero hasta llegar al precio justo.',
      hasPuesto: 'Has puesto: {total}',
      quitarUltima: '↩ Quitar última',
      vaciar: '🗑 Vaciar',
      comprobar: 'Comprobar',
      escucharPrecio: 'Escuchar el precio',
      cuesta: '{nombre}: {precio}',
      faltaDinero1: 'Falta dinero. Mira el precio y mira lo que has puesto.',
      sobraDinero1: 'Sobra dinero. Mira el precio y mira lo que has puesto.',
      faltaDinero2: 'Faltan {dif}. Añade más dinero.',
      sobraDinero2: 'Sobran {dif}. Quita algún dinero.',
      resumenPagar: 'Has pagado justo a la primera {n} de {t}.',
      btnAyuda: '💡 Ayuda',
      ariaEscucharAyuda: 'Escuchar la ayuda',
      ayudaPagar1: 'Mira el precio y mira tu total. ¿Cuál es el dinero más grande que cabe sin pasarte?',
      ayudaPagar2: 'Toca el dinero marcado: cabe sin pasarte del precio.',
      ayudaQuita1: 'Mira tu total. ¿Has puesto más dinero que el precio?',
      ayudaQuita2: 'Toca el botón marcado para quitar dinero.',
      ayudaComprobar: 'Tu total es igual al precio. ¡Toca Comprobar!'
    },
    en: {
      title: '💶 The Coin Purse',
      instruccion: 'Here you practise real money: counting it, paying, checking the change and saving.',
      volverMenu: '← Menu',
      elegirNivel: 'Choose the level',
      vecesTexto: '{n} times',
      btnOtroNivel: 'Choose another level',
      menuContar: 'How much is there?',
      menuContarDetalle: 'Look at the money and choose the total.',
      menuPagar: 'Pay the exact price',
      menuPagarDetalle: 'Touch the money up to the exact price.',
      menuConQuePago: 'What do I pay with?',
      menuConQuePagoDetalle: 'Choose the money that is enough.',
      menuCambio: 'Is the change right?',
      menuCambioDetalle: 'Count the change and decide.',
      menuHucha: 'The Piggy Bank',
      menuHuchaDetalle: 'How much is missing to buy it?',
      menuRedondeo: 'More or less',
      menuRedondeoDetalle: 'How much is it, without counting cents?',
      instruccionContar: 'How much money is there? Count the money and choose the total.',
      instruccionConQuePago: 'You do not have the exact price. Choose the money that is enough to pay.',
      instruccionCambio: 'You have paid. Count the change and decide if it is right.',
      instruccionHucha: 'You want to buy something. Count your money and work out how much is missing.',
      instruccionRedondeo: 'Look at the price. Say how much it is, more or less, without counting the cents.',
      /* (Money words — euro, cents, coin of… — live in the shared
         module assets/js/dinero.js.) */
      anadirDinero: 'Add {d}',
      /* --- How much is there? --- */
      contarPregunta: 'How much money is there?',
      ariaMesa: 'Money on the table',
      pistaContar: 'Count again, slowly. Start with the biggest money.',
      explicacionBien: 'That is it! There is {d}. In total, {total}.',
      explicacionCasi: 'Look: there is {d}. In total, {total}.',
      resumenContar: 'You counted correctly {n} out of {t}.',
      /* --- What do I pay with? --- */
      enunciadoConQuePago: '{nombre} costs {precio}. You do not have the exact price. What do you pay with?',
      pistaConQuePago: 'Look at the price. Is that money more or less than the price?',
      explicacionPagoBien: 'That is it! You pay with {pagado}. You get {cambio} back.',
      explicacionPagoCasi: 'Look: that money is less than the price. You pay with {pagado}. You get {cambio} back.',
      teDevuelven: 'You get back:',
      resumenConQuePago: 'You paid right first time {n} out of {t}.',
      /* --- Is the change right? --- */
      enunciadoCambio: 'It costs {precio}. You pay with {pagado}. You get this back. Is the change right?',
      si: 'Yes',
      no: 'No',
      pistaCambio: 'Count the money on the table. How much did you get back?',
      explicacionCambioBien: 'The right change is {bueno}. You got {mostrado}. It is right!',
      explicacionCambioFalta: 'The right change is {bueno}. You got {mostrado}. It is wrong: money is missing.',
      explicacionCambioSobra: 'The right change is {bueno}. You got {mostrado}. It is wrong: you got too much.',
      resumenCambio: 'You checked correctly {n} out of {t}.',
      /* --- The Piggy Bank --- */
      enunciadoHucha: 'You want to buy {nombre}. It costs {precio}. You have this money. How much is missing?',
      pistaHucha: 'First count the money on the table. Then look at the price.',
      explicacionHuchaBien: 'That is it! It costs {precio}. You have {tienes}. {falta} is missing.',
      explicacionHuchaCasi: 'Look: it costs {precio}. You have {tienes}. {falta} is missing.',
      resumenHucha: 'You worked it out correctly {n} out of {t}.',
      /* --- More or less --- */
      enunciadoRedondeo: '{nombre} costs {precio}. How much is that, more or less?',
      unosEuros: 'about {n} €',
      pistaRedondeo: 'Look at the cents. Are they closer to the euro above or the euro below?',
      explicacionRedondeoBien: 'That is it! {precio} is very close to {n} €. We say: about {n} €.',
      explicacionRedondeoCasi: 'Look: {precio} is very close to {n} €. We say: about {n} €.',
      explicacionRedondeoMedioBien: 'That is it! {precio} ends in 50. When it ends in 50, we say the euro above: about {n} €.',
      explicacionRedondeoMedioCasi: 'Look: {precio} ends in 50. When it ends in 50, we say the euro above: about {n} €.',
      resumenRedondeo: 'You estimated correctly {n} out of {t}.',
      /* --- Pay the exact price --- */
      pagarInstruccion: 'Look at the price. Touch the money until you reach the exact price.',
      hasPuesto: 'You have put in: {total}',
      quitarUltima: '↩ Remove last',
      vaciar: '🗑 Empty',
      comprobar: 'Check',
      escucharPrecio: 'Listen to the price',
      cuesta: '{nombre}: {precio}',
      faltaDinero1: 'Not enough money. Look at the price and look at what you have put in.',
      sobraDinero1: 'Too much money. Look at the price and look at what you have put in.',
      faltaDinero2: '{dif} missing. Add more money.',
      sobraDinero2: '{dif} too much. Remove some money.',
      resumenPagar: 'You paid the exact price first time {n} out of {t}.',
      btnAyuda: '💡 Help',
      ariaEscucharAyuda: 'Listen to the help',
      ayudaPagar1: 'Look at the price and look at your total. What is the biggest money that fits without going over?',
      ayudaPagar2: 'Touch the marked money: it fits without going over the price.',
      ayudaQuita1: 'Look at your total. Have you put in more money than the price?',
      ayudaQuita2: 'Touch the marked button to remove money.',
      ayudaComprobar: 'Your total equals the price. Touch Check!'
    }
  });
})();
