(function () {
  'use strict';

  App.i18n.register({
    title: '🔢 Las Tablas',
    instruction: 'Aprende a contar de cabeza, sumar y multiplicar con puntos de colores.',
    chooseOperation: 'Elige qué quieres practicar.',
    stepsName: 'Contar de cabeza',
    stepsDetail: 'Suma o resta 1, 2 o 3 sin usar los dedos.',
    addName: 'Tablas de sumar',
    addDetail: 'Junta puntos de dos colores y cuenta el total.',
    decomposeName: 'Descomponer números',
    decomposeDetail: 'Llega primero a 10: 7 + 5 es 7 + 3 y 2 más.',
    multiplyName: 'Tablas de multiplicar',
    multiplyDetail: 'Repite grupos de puntos, cada grupo de un color.',
    chooseTable: 'Elige una tabla.',
    chooseLevel: 'Elige un nivel.',
    tableButton: 'Tabla del {n}',
    stepLevel: 'Sumar y restar {n}',
    tableTitleAdd: 'Tabla de sumar del {n}',
    tableTitleMultiply: 'Tabla de multiplicar del {n}',
    learnInstruction: 'Toca una fila para verla con puntos y escucharla.',
    practiceTable: 'Practicar esta tabla',
    backToTables: '← Elegir otra tabla',
    backToLevels: '← Elegir otro nivel',
    quizPrompt: '¿Cuánto es {a} {symbol} {b}?',
    progress: '{current} de {total}',
    hintAdd: 'Pista: cuenta todos los puntos, uno a uno.',
    hintMultiply: 'Pista: son {b} grupos de {a} puntos. Cuenta grupo a grupo.',
    hintStepsAdd: 'Pista: empieza en {a} y cuenta {b} más, de uno en uno.',
    hintStepsSubtract: 'Pista: empieza en {a} y cuenta {b} hacia atrás.',
    hintDecompose: 'Pista: de {a} a 10 faltan {toTen}. Llega primero a 10.',
    explainAdd: '{a} puntos azules y {b} puntos naranjas son {result} puntos en total.',
    explainMultiply: '{b} grupos de {a} puntos son {result} puntos en total.',
    explainStepsAdd: '{a} y {b} más son {result}.',
    explainStepsSubtract: '{a} menos {b} son {result}. Los puntos tachados ya no se cuentan.',
    explainDecompose: '{a} + {b} es lo mismo que {a} + {toTen} + {rest}. Primero 10, y {rest} más: {result}.',
    speakAdd: '{a} más {b} son {result}',
    speakSubtract: '{a} menos {b} son {result}',
    speakMultiply: '{a} por {b} es {result}',
    addWord: 'más',
    subtractWord: 'menos',
    multiplyWord: 'por',
    visualAdd: '{a} puntos de un color y {b} puntos de otro color',
    visualMultiply: '{b} grupos de {a} puntos, cada grupo de un color',
    visualStepsAdd: '{a} puntos de un color y {b} puntos de otro color',
    visualStepsSubtract: '{a} puntos, con {b} tachados',
    visualDecompose: '{a} puntos de un color, {toTen} de otro para llegar a 10 y {rest} más',
    roundSummary: 'Has resuelto {count} operaciones. Ahora tienes {stars} estrellas.',
    chooseAnotherTable: 'Elegir otra tabla',
    chooseAnotherLevel: 'Elegir otro nivel',
    changeOperation: 'Cambiar de actividad'
  }, 'es');
})();
