/* 32 non-graphic preventive simulations, grouped into four topics.
   Real-life (offline) counterpart to tools/social-safety (which covers
   digital/online risks). No clinical or anatomical vocabulary: the
   correct answer always reinforces body autonomy and points to a
   trusted adult or health professional — this activity never gives
   direct medical instructions. */
var DATA = {
  es: {
    porRonda: 5,
    niveles: [
      {
        id: 'consentimiento', nombre: 'Mi cuerpo y el consentimiento', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🤗', situacion: 'Un familiar te pide un abrazo pero tú no quieres.', opciones: ['Digo que no quiero, y está bien decirlo', 'Abrazo aunque no quiera, para no ofender', 'Me escondo sin decir nada'], correcta: 0, pista: '🤔 ¿Tu cuerpo es tuyo? ¿Puedes decidir?', explicacion: '✅ Tu cuerpo es tuyo. Puedes decir que no a un abrazo, aunque sea alguien conocido.' },
          { picto: '🏥', situacion: 'Vas al médico y necesita revisarte el cuerpo.', opciones: ['Pregunto si puede venir conmigo una persona de confianza', 'Voy sola/o sin preguntar nada', 'Digo que no a cualquier revisión'], correcta: 0, pista: '🤔 ¿Puedes pedir que alguien de confianza te acompañe?', explicacion: '✅ Puedes pedir que te acompañe una persona de confianza en una revisión médica. Es tu derecho.' },
          { picto: '🚫', situacion: 'Alguien te toca de una forma que no te gusta.', opciones: ['Digo que pare y lo cuento a una persona adulta de confianza', 'No digo nada para no molestar', 'Espero a que se le pase'], correcta: 0, pista: '🤔 ¿Puedes decir que pare?', explicacion: '✅ Puedes decir que pare, siempre. Y puedes contarlo a alguien de confianza.' },
          { picto: '🔒', situacion: 'Quieres cerrar la puerta cuando te cambias de ropa.', opciones: ['Cierro la puerta, mi intimidad importa', 'No cierro la puerta, da igual', 'Solo cierro si hay alguien mirando'], correcta: 0, pista: '🤔 ¿Tienes derecho a intimidad?', explicacion: '✅ Tienes derecho a intimidad. Puedes cerrar la puerta cuando lo necesites.' },
          { picto: '🙅', situacion: 'Una persona insiste en besarte y tú no quieres.', opciones: ['Digo que no quiero, las veces que haga falta', 'Le dejo para que no se enfade', 'Me quedo quieta/o sin decir nada'], correcta: 0, pista: '🤔 ¿Puedes repetir un no las veces que haga falta?', explicacion: '✅ Puedes decir que no las veces que haga falta. Un no se respeta siempre.' },
          { picto: '🧑‍⚕️', situacion: 'En una consulta médica te piden quitarte ropa para una revisión necesaria.', opciones: ['Pregunto para qué es y pido que esté alguien de confianza', 'Lo hago sin preguntar nada', 'Me niego a cualquier revisión'], correcta: 0, pista: '🤔 ¿Puedes preguntar y pedir compañía?', explicacion: '✅ Puedes preguntar para qué es una revisión y pedir que te acompañe alguien de confianza.' },
          { picto: '💬', situacion: 'Un amigo te dice que si de verdad confías en él, le dejarás ver tu cuerpo.', opciones: ['Le digo que la confianza no obliga a eso', 'Se lo permito para que no se enfade', 'Dudo pero acabo aceptando'], correcta: 0, pista: '🤔 ¿La confianza obliga a algo con tu cuerpo?', explicacion: '✅ La confianza no obliga a nada con tu cuerpo. Un amigo de verdad respeta un no.' },
          { picto: '🖐️', situacion: 'No sabes si puedes decir que no a algo que no te gusta con tu cuerpo.', opciones: ['Sí puedo decir que no, siempre, aunque ya haya empezado', 'Solo puedo decir que no al principio', 'Si ya dije que sí antes, no puedo cambiar de idea'], correcta: 0, pista: '🤔 ¿Puedes cambiar de idea en cualquier momento?', explicacion: '✅ Puedes decir que no en cualquier momento, aunque antes dijeras que sí.' }
        ]
      },
      {
        id: 'relaciones', nombre: 'Relaciones sanas', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🚷', situacion: 'Tu pareja no te deja ver a tus amigos/as.', opciones: ['Hablo con alguien de confianza, eso no es normal', 'Dejo de ver a mis amigos/as para tener paz', 'Le doy explicaciones cada vez que quiero salir'], correcta: 0, pista: '🤔 ¿Una relación sana te aleja de la gente que quieres?', explicacion: '✅ Una relación sana no te aísla de la gente que quieres. Eso es una señal de alarma.' },
          { picto: '📱', situacion: 'Tu pareja quiere leer todos tus mensajes y saber dónde estás siempre.', opciones: ['Pongo un límite: mi privacidad importa, y pido apoyo si insiste', 'Le doy acceso a todo para que confíe en mí', 'Le enseño solo algunos mensajes'], correcta: 0, pista: '🤔 ¿La confianza necesita controlar todo lo que haces?', explicacion: '✅ Controlar tus mensajes y tus movimientos no es amor, es control. Puedes pedir ayuda.' },
          { picto: '😢', situacion: 'Después de una discusión, tu pareja te dice que es tu culpa de todo lo que pasa.', opciones: ['Pienso que no siempre es culpa mía, y hablo con alguien de confianza', 'Le creo, seguro que tiene razón', 'Me disculpo aunque no sepa por qué'], correcta: 0, pista: '🤔 ¿En una pareja la culpa es siempre de una sola persona?', explicacion: '✅ En una relación sana, la responsabilidad se comparte. Nadie tiene siempre toda la culpa.' },
          { picto: '🎁', situacion: 'Tu pareja te hace regalos caros y luego te pide cosas que no quieres hacer.', opciones: ['Digo que no, un regalo no me obliga a nada', 'Hago lo que pide porque me hizo un regalo', 'Acepto para no parecer desagradecido/a'], correcta: 0, pista: '🤔 ¿Un regalo te obliga a algo?', explicacion: '✅ Un regalo no te obliga a nada. Puedes decir que no aunque te hayan hecho un regalo.' },
          { picto: '🚪', situacion: 'Quieres terminar una relación pero tienes miedo de decirlo.', opciones: ['Tengo derecho a terminar una relación cuando quiera, y puedo pedir apoyo', 'Sigo en la relación aunque no quiera', 'Espero a que la otra persona lo adivine'], correcta: 0, pista: '🤔 ¿Tienes derecho a decidir terminar una relación?', explicacion: '✅ Tienes derecho a terminar una relación cuando quieras. Una persona de confianza puede ayudarte a hacerlo con seguridad.' },
          { picto: '👏', situacion: 'Tu pareja te anima a hacer cosas que te gustan y respeta cuando dices que no.', opciones: ['Eso es una señal de una relación sana', 'Eso significa que no le importo', 'Debería preocuparme por eso'], correcta: 0, pista: '🤔 ¿El respeto y el apoyo son buenas señales?', explicacion: '✅ Respetar tus gustos y tus límites es una señal de una relación sana. ¡Bien reconocido!' },
          { picto: '😨', situacion: 'Tienes miedo de tu pareja porque a veces grita o rompe cosas cuando se enfada.', opciones: ['Lo cuento a una persona de confianza, eso no es seguro', 'No digo nada para no provocarle', 'Pienso que es normal si luego pide perdón'], correcta: 0, pista: '🤔 ¿Dar miedo es parte de una relación sana?', explicacion: '✅ Si tienes miedo de tu pareja, eso no es seguro. Cuéntaselo a una persona de confianza.' },
          { picto: '🤝', situacion: 'No sabes si lo que sientes en tu relación es normal o no.', opciones: ['Hablarlo con una persona de confianza me puede ayudar a verlo claro', 'Prefiero no hablarlo con nadie', 'Pienso que preguntar es exagerar'], correcta: 0, pista: '🤔 ¿Hablarlo con alguien puede ayudarte?', explicacion: '✅ Hablar con una persona de confianza o un profesional te puede ayudar a ver la relación con más claridad.' }
        ]
      },
      {
        id: 'anticoncepcion', nombre: 'Anticoncepción', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '❓', situacion: 'Quieres saber qué métodos anticonceptivos existen.', opciones: ['Pregunto a un profesional de la salud (médico, matrona, centro de salud)', 'Busco solo en internet y lo que diga una amistad', 'No pregunto porque me da vergüenza'], correcta: 0, pista: '🤔 ¿Quién te puede explicar esto de forma segura?', explicacion: '✅ Un profesional de la salud te explica las opciones y cuál te conviene, sin ningún problema.' },
          { picto: '💊', situacion: 'Una amistad te da una pastilla y dice que es anticonceptiva.', opciones: ['No la tomo sin que me lo indique un profesional de la salud', 'La tomo porque mi amistad lo dice', 'La tomo sin preguntar nada'], correcta: 0, pista: '🤔 ¿Puedes tomar medicinas sin que te las indique un profesional?', explicacion: '✅ Nunca tomes una medicina que no te indique un profesional de la salud. Puede ser peligroso.' },
          { picto: '👩‍⚕️', situacion: 'No sabes a quién preguntar sobre anticoncepción.', opciones: ['Puedo ir a un centro de salud o hablar con mi médico de cabecera', 'Solo puedo preguntarlo a mis amistades', 'No hay nadie a quien preguntar'], correcta: 0, pista: '🤔 ¿Existen lugares donde te pueden ayudar con esto?', explicacion: '✅ Un centro de salud o tu médico de cabecera pueden ayudarte con toda confianza y sin juzgarte.' },
          { picto: '🤰', situacion: 'Te preocupa un posible embarazo y no sabes qué hacer.', opciones: ['Voy a un centro de salud o se lo cuento a una persona de confianza', 'No hago nada y espero a ver qué pasa', 'Se lo pregunto solo a amistades'], correcta: 0, pista: '🤔 ¿Quién puede ayudarte de forma segura y rápida?', explicacion: '✅ Un centro de salud te puede informar y ayudar cuanto antes. No tienes que resolverlo sola/o.' },
          { picto: '🙋', situacion: 'Te da vergüenza preguntar sobre anticoncepción en la consulta médica.', opciones: ['Aun con vergüenza, tengo derecho a preguntar y me pueden ayudar', 'No pregunto por la vergüenza', 'Espero a que se me pase la vergüenza para siempre'], correcta: 0, pista: '🤔 ¿La vergüenza debe impedir que pidas ayuda?', explicacion: '✅ Los profesionales de la salud están para ayudarte, sin juzgarte. Preguntar es un derecho.' },
          { picto: '🔐', situacion: 'Quieres que lo que hables con un profesional de la salud sea privado.', opciones: ['Puedo pedir que sea confidencial, es mi derecho', 'Todo lo que digo se cuenta a mi familia sin que yo lo sepa', 'No puedo pedir privacidad en la consulta'], correcta: 0, pista: '🤔 ¿Tienes derecho a la privacidad en una consulta?', explicacion: '✅ Tienes derecho a la confidencialidad con un profesional de la salud. Puedes preguntarlo tranquilamente.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Tu pareja no quiere usar ningún método de protección y tú sí quieres.', opciones: ['Mi decisión sobre mi cuerpo importa, y puedo pedir apoyo si insiste', 'Hago lo que mi pareja prefiera', 'No digo nada para evitar una discusión'], correcta: 0, pista: '🤔 ¿Tu opinión sobre tu propio cuerpo cuenta?', explicacion: '✅ Tu decisión sobre tu cuerpo y tu salud importa siempre. Puedes pedir ayuda si no se respeta.' },
          { picto: '📅', situacion: 'No entiendes bien la información que te ha dado un profesional de la salud.', opciones: ['Puedo pedir que me lo expliquen otra vez, más despacio', 'Finjo que lo he entendido', 'No vuelvo a preguntar nunca más'], correcta: 0, pista: '🤔 ¿Puedes pedir que te lo expliquen de otra forma?', explicacion: '✅ Puedes pedir que te lo expliquen de nuevo, más despacio o con dibujos. Es tu derecho entenderlo.' }
        ]
      },
      {
        id: 'higiene', nombre: 'Higiene y salud sexual', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🩹', situacion: 'Notas algo raro en tu cuerpo y no sabes si es normal.', opciones: ['Voy al médico o al centro de salud a preguntar', 'Espero a ver si se pasa solo', 'Se lo pregunto solo a una amistad'], correcta: 0, pista: '🤔 ¿Quién puede revisarlo con seguridad?', explicacion: '✅ Un profesional de la salud puede revisarlo y explicarte qué pasa, sin ningún problema.' },
          { picto: '🧼', situacion: 'Quieres saber qué hábitos de higiene son importantes para tu cuerpo.', opciones: ['Pregunto a un profesional de la salud o a una persona de confianza', 'No pregunto porque debería saberlo ya', 'Copio lo que hacen mis amistades sin preguntar'], correcta: 0, pista: '🤔 ¿Está bien pedir que te lo expliquen?', explicacion: '✅ Puedes preguntar sobre higiene sin vergüenza. Un profesional o una persona de confianza te puede orientar.' },
          { picto: '🛡️', situacion: 'Alguien te dice que usar protección no es necesario si confías en la otra persona.', opciones: ['La protección es importante, confiar no la sustituye', 'Le creo y no uso protección', 'Solo la uso si me lo piden'], correcta: 0, pista: '🤔 ¿La confianza sustituye a la protección?', explicacion: '✅ La confianza no sustituye a la protección. Un profesional de la salud te puede explicar por qué es importante.' },
          { picto: '🚑', situacion: 'Te preocupa haber estado en una situación de riesgo para tu salud.', opciones: ['Voy a un centro de salud cuanto antes a preguntar', 'Espero a ver si tengo síntomas', 'No se lo cuento a nadie por vergüenza'], correcta: 0, pista: '🤔 ¿Es mejor preguntar pronto?', explicacion: '✅ Ante cualquier duda, un centro de salud te puede atender pronto y con confidencialidad.' },
          { picto: '🗣️', situacion: 'Te da vergüenza hablar de estos temas con un profesional de la salud.', opciones: ['Los profesionales están acostumbrados y no me van a juzgar', 'Prefiero no ir nunca a preguntar esto', 'Solo hablo de esto con amistades'], correcta: 0, pista: '🤔 ¿Un profesional de la salud está para ayudarte sin juzgar?', explicacion: '✅ Un profesional de la salud ha hablado de esto muchas veces. Está para ayudarte, no para juzgarte.' },
          { picto: '🧴', situacion: 'No sabes si necesitas usar protección en una relación.', opciones: ['Puedo preguntarlo a un profesional de la salud para estar segura/o', 'Doy por hecho que no hace falta', 'Le pregunto solo a mi pareja'], correcta: 0, pista: '🤔 ¿A quién puedes preguntar para estar segura/o?', explicacion: '✅ Un profesional de la salud te puede explicar cuándo y por qué usar protección.' },
          { picto: '📋', situacion: 'Un profesional de la salud te propone hacerte una revisión rutinaria de salud sexual.', opciones: ['Puedo aceptar y preguntar todo lo que necesite saber', 'Digo que no porque me da miedo', 'Lo dejo para otro momento sin decidir'], correcta: 0, pista: '🤔 ¿Una revisión rutinaria puede ayudarte a cuidarte?', explicacion: '✅ Una revisión rutinaria te ayuda a cuidar tu salud. Puedes preguntar todo lo que necesites.' },
          { picto: '💗', situacion: 'No sabes si lo que sientes sobre tu cuerpo o tu salud es normal preguntarlo.', opciones: ['Siempre es normal preguntar sobre mi cuerpo y mi salud', 'Solo puedo preguntar si es algo grave', 'Debería saberlo todo sin preguntar'], correcta: 0, pista: '🤔 ¿Siempre está bien preguntar sobre tu salud?', explicacion: '✅ Siempre está bien preguntar sobre tu cuerpo y tu salud. No hay preguntas tontas.' }
        ]
      }
    ]
  },
  en: {
    porRonda: 5,
    niveles: [
      {
        id: 'consent', nombre: 'My body and consent', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🤗', situacion: 'A family member asks for a hug but you do not want one.', opciones: ['I say I do not want to, and that is okay', 'I hug anyway so I do not offend them', 'I hide without saying anything'], correcta: 0, pista: '🤔 Is your body yours? Can you decide?', explicacion: '✅ Your body is yours. You can say no to a hug, even from someone you know.' },
          { picto: '🏥', situacion: 'You go to the doctor and they need to examine your body.', opciones: ['I ask if a trusted person can come with me', 'I go alone without asking anything', 'I say no to any examination'], correcta: 0, pista: '🤔 Can you ask someone you trust to come with you?', explicacion: '✅ You can ask a trusted person to be with you during a medical exam. It is your right.' },
          { picto: '🚫', situacion: 'Someone touches you in a way you do not like.', opciones: ['I say stop and tell a trusted adult', 'I say nothing so I do not bother them', 'I wait for it to stop on its own'], correcta: 0, pista: '🤔 Can you say stop?', explicacion: '✅ You can always say stop. And you can tell someone you trust.' },
          { picto: '🔒', situacion: 'You want to close the door when you change your clothes.', opciones: ['I close the door, my privacy matters', 'I do not close it, it does not matter', 'I only close it if someone is watching'], correcta: 0, pista: '🤔 Do you have a right to privacy?', explicacion: '✅ You have a right to privacy. You can close the door whenever you need to.' },
          { picto: '🙅', situacion: 'Someone keeps trying to kiss you and you do not want to.', opciones: ['I say no, as many times as I need to', 'I let them so they do not get upset', 'I stay still and say nothing'], correcta: 0, pista: '🤔 Can you repeat a no as many times as you need?', explicacion: '✅ You can say no as many times as you need. A no is always respected.' },
          { picto: '🧑‍⚕️', situacion: 'At a medical appointment they ask you to remove clothing for a needed exam.', opciones: ['I ask what it is for and ask for a trusted person to be there', 'I do it without asking anything', 'I refuse any exam at all'], correcta: 0, pista: '🤔 Can you ask questions and ask for company?', explicacion: '✅ You can ask what an exam is for and ask a trusted person to be with you.' },
          { picto: '💬', situacion: 'A friend says that if you really trust them, you will let them see your body.', opciones: ['I tell them trust does not require that', 'I allow it so they do not get upset', 'I hesitate but end up agreeing'], correcta: 0, pista: '🤔 Does trust require anything with your body?', explicacion: '✅ Trust does not require anything with your body. A real friend respects a no.' },
          { picto: '🖐️', situacion: 'You are not sure if you can say no to something you do not like with your body.', opciones: ['Yes, I can say no, always, even if it already started', 'I can only say no at the beginning', 'If I said yes before, I cannot change my mind'], correcta: 0, pista: '🤔 Can you change your mind at any moment?', explicacion: '✅ You can say no at any moment, even if you said yes before.' }
        ]
      },
      {
        id: 'relationships', nombre: 'Healthy relationships', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🚷', situacion: 'Your partner does not let you see your friends.', opciones: ['I talk to someone I trust, that is not normal', 'I stop seeing my friends for peace', 'I explain myself every time I want to go out'], correcta: 0, pista: '🤔 Does a healthy relationship keep you away from people you love?', explicacion: '✅ A healthy relationship does not isolate you from people you love. That is a warning sign.' },
          { picto: '📱', situacion: 'Your partner wants to read all your messages and always know where you are.', opciones: ['I set a boundary: my privacy matters, and I ask for support if they insist', 'I give them access to everything so they trust me', 'I only show them some messages'], correcta: 0, pista: '🤔 Does trust need to control everything you do?', explicacion: '✅ Controlling your messages and movements is not love, it is control. You can ask for help.' },
          { picto: '😢', situacion: 'After an argument, your partner tells you everything that happens is your fault.', opciones: ['I think it is not always my fault, and I talk to someone I trust', 'I believe them, they are probably right', 'I apologise even if I do not know why'], correcta: 0, pista: '🤔 In a couple, is the blame always one person’s?', explicacion: '✅ In a healthy relationship, responsibility is shared. No one is always entirely to blame.' },
          { picto: '🎁', situacion: 'Your partner gives you expensive gifts and then asks for things you do not want to do.', opciones: ['I say no, a gift does not obligate me to anything', 'I do what they ask because they gave me a gift', 'I agree so I do not seem ungrateful'], correcta: 0, pista: '🤔 Does a gift obligate you to something?', explicacion: '✅ A gift does not obligate you to anything. You can say no even after receiving a gift.' },
          { picto: '🚪', situacion: 'You want to end a relationship but you are afraid to say it.', opciones: ['I have the right to end a relationship whenever I want, and I can ask for support', 'I stay in the relationship even if I do not want to', 'I wait for the other person to guess'], correcta: 0, pista: '🤔 Do you have the right to decide to end a relationship?', explicacion: '✅ You have the right to end a relationship whenever you want. A trusted person can help you do it safely.' },
          { picto: '👏', situacion: 'Your partner encourages things you enjoy and respects it when you say no.', opciones: ['That is a sign of a healthy relationship', 'That means I do not matter to them', 'I should worry about that'], correcta: 0, pista: '🤔 Are respect and support good signs?', explicacion: '✅ Respecting your likes and your limits is a sign of a healthy relationship. Well spotted!' },
          { picto: '😨', situacion: 'You are afraid of your partner because they sometimes shout or break things when angry.', opciones: ['I tell someone I trust, that is not safe', 'I say nothing so I do not provoke them', 'I think it is normal if they apologise afterwards'], correcta: 0, pista: '🤔 Is fear part of a healthy relationship?', explicacion: '✅ If you are afraid of your partner, that is not safe. Tell someone you trust.' },
          { picto: '🤝', situacion: 'You are not sure if what you feel in your relationship is normal or not.', opciones: ['Talking about it with someone I trust can help me see it clearly', 'I prefer not to talk about it with anyone', 'I think asking about it is overreacting'], correcta: 0, pista: '🤔 Can talking to someone help you?', explicacion: '✅ Talking to a trusted person or a professional can help you see the relationship more clearly.' }
        ]
      },
      {
        id: 'contraception', nombre: 'Contraception', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '❓', situacion: 'You want to know what contraceptive methods exist.', opciones: ['I ask a health professional (doctor, midwife, health centre)', 'I only search online or ask a friend', 'I do not ask because I feel embarrassed'], correcta: 0, pista: '🤔 Who can explain this to you safely?', explicacion: '✅ A health professional explains the options and which one suits you, with no problem at all.' },
          { picto: '💊', situacion: 'A friend gives you a pill and says it is a contraceptive.', opciones: ['I do not take it unless a health professional tells me to', 'I take it because my friend says so', 'I take it without asking anything'], correcta: 0, pista: '🤔 Can you take medicine without a professional telling you to?', explicacion: '✅ Never take medicine that a health professional has not told you to take. It can be dangerous.' },
          { picto: '👩‍⚕️', situacion: 'You do not know who to ask about contraception.', opciones: ['I can go to a health centre or talk to my family doctor', 'I can only ask my friends', 'There is no one to ask'], correcta: 0, pista: '🤔 Are there places that can help you with this?', explicacion: '✅ A health centre or your family doctor can help you, confidentially and without judging you.' },
          { picto: '🤰', situacion: 'You are worried about a possible pregnancy and do not know what to do.', opciones: ['I go to a health centre or tell someone I trust', 'I do nothing and wait to see what happens', 'I only ask friends about it'], correcta: 0, pista: '🤔 Who can help you safely and quickly?', explicacion: '✅ A health centre can inform and help you as soon as possible. You do not have to solve it alone.' },
          { picto: '🙋', situacion: 'You feel embarrassed asking about contraception at a medical appointment.', opciones: ['Even with embarrassment, I have the right to ask and they can help me', 'I do not ask because of embarrassment', 'I wait for the embarrassment to go away forever'], correcta: 0, pista: '🤔 Should embarrassment stop you asking for help?', explicacion: '✅ Health professionals are there to help you, without judging. Asking is a right.' },
          { picto: '🔐', situacion: 'You want what you discuss with a health professional to stay private.', opciones: ['I can ask for it to be confidential, it is my right', 'Everything I say is told to my family without me knowing', 'I cannot ask for privacy at an appointment'], correcta: 0, pista: '🤔 Do you have a right to privacy at an appointment?', explicacion: '✅ You have a right to confidentiality with a health professional. You can ask about it calmly.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Your partner does not want to use any protection and you do.', opciones: ['My decision about my body matters, and I can ask for support if they insist', 'I do what my partner prefers', 'I say nothing to avoid an argument'], correcta: 0, pista: '🤔 Does your opinion about your own body count?', explicacion: '✅ Your decision about your body and your health always matters. You can ask for help if it is not respected.' },
          { picto: '📅', situacion: 'You do not fully understand the information a health professional gave you.', opciones: ['I can ask them to explain it again, more slowly', 'I pretend I understood', 'I never ask again'], correcta: 0, pista: '🤔 Can you ask for it to be explained differently?', explicacion: '✅ You can ask for it to be explained again, more slowly or with pictures. It is your right to understand it.' }
        ]
      },
      {
        id: 'health', nombre: 'Hygiene and sexual health', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🩹', situacion: 'You notice something unusual on your body and do not know if it is normal.', opciones: ['I go to the doctor or health centre to ask', 'I wait to see if it goes away on its own', 'I only ask a friend about it'], correcta: 0, pista: '🤔 Who can check it safely?', explicacion: '✅ A health professional can check it and explain what is happening, with no problem at all.' },
          { picto: '🧼', situacion: 'You want to know which hygiene habits matter for your body.', opciones: ['I ask a health professional or a trusted person', 'I do not ask because I should already know', 'I copy what my friends do without asking'], correcta: 0, pista: '🤔 Is it okay to ask for it to be explained?', explicacion: '✅ You can ask about hygiene without embarrassment. A professional or trusted person can guide you.' },
          { picto: '🛡️', situacion: 'Someone tells you that using protection is not needed if you trust the other person.', opciones: ['Protection matters, trust does not replace it', 'I believe them and do not use protection', 'I only use it if I am asked to'], correcta: 0, pista: '🤔 Does trust replace protection?', explicacion: '✅ Trust does not replace protection. A health professional can explain why it matters.' },
          { picto: '🚑', situacion: 'You are worried you may have been in a situation that was risky for your health.', opciones: ['I go to a health centre as soon as possible to ask', 'I wait to see if I get symptoms', 'I do not tell anyone out of embarrassment'], correcta: 0, pista: '🤔 Is it better to ask early?', explicacion: '✅ Whenever you are unsure, a health centre can see you soon and confidentially.' },
          { picto: '🗣️', situacion: 'You feel embarrassed talking about these topics with a health professional.', opciones: ['Professionals are used to this and will not judge me', 'I would rather never go to ask about this', 'I only talk about this with friends'], correcta: 0, pista: '🤔 Is a health professional there to help without judging?', explicacion: '✅ A health professional has talked about this many times. They are there to help you, not to judge you.' },
          { picto: '🧴', situacion: 'You are not sure if you need to use protection in a relationship.', opciones: ['I can ask a health professional to be sure', 'I assume it is not needed', 'I only ask my partner'], correcta: 0, pista: '🤔 Who can you ask to be sure?', explicacion: '✅ A health professional can explain when and why to use protection.' },
          { picto: '📋', situacion: 'A health professional offers you a routine sexual health check-up.', opciones: ['I can accept and ask everything I need to know', 'I say no because it scares me', 'I put it off without deciding'], correcta: 0, pista: '🤔 Can a routine check-up help you take care of yourself?', explicacion: '✅ A routine check-up helps you take care of your health. You can ask everything you need to.' },
          { picto: '💗', situacion: 'You are not sure if it is normal to ask questions about your body or your health.', opciones: ['It is always normal to ask about my body and my health', 'I can only ask if it is something serious', 'I should know everything without asking'], correcta: 0, pista: '🤔 Is it always okay to ask about your health?', explicacion: '✅ It is always okay to ask about your body and your health. There are no silly questions.' }
        ]
      }
    ]
  }
};
