/* ============================================================
   Apptonomia — Textos de La Tienda / The Shop (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   (Las palabras del dinero viven en assets/js/dinero.js, dinero.*)
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '🏪 La Tienda',
      instruccion: 'Aquí usas el dinero como en la vida real: haces una compra entera, controlas lo que te queda y piensas si un precio está bien.',
      volverMenu: '← Menú',
      elegirNivel: 'Elige el nivel',
      vecesTexto: '{n} veces',
      btnOtroNivel: 'Elegir otro nivel',
      si: 'Sí',
      no: 'No',
      ariaMesa: 'Dinero sobre la mesa',
      menuTienda: 'Una compra',
      menuTiendaDetalle: 'De principio a fin: mira, paga y revisa.',
      menuQuedame: '¿Qué me queda?',
      menuQuedameDetalle: 'Vas comprando. Calcula lo que te queda.',
      menuMucho: '¿Mucho o poco?',
      menuMuchoDetalle: '¿Ese precio está bien o es demasiado?',
      instruccionTienda: 'Vas a hacer una compra entera: mira si te llega, paga y revisa el cambio.',
      instruccionQuedame: 'Empiezas con un dinero. Vas comprando cosas. Calcula cuánto te queda.',
      instruccionMucho: 'Mira el producto y su precio. Piensa si está bien o es demasiado dinero.',
      /* --- Una compra (pasos) --- */
      compraDe: 'Compra {n} de {t}',
      paso1Enunciado: '{nombre} cuesta {precio}. Este es tu dinero. ¿Te llega?',
      pistaPaso1: 'Cuenta tu dinero, despacio. Después mira el precio.',
      explicaLlega: 'Tienes {total}. El precio es {precio}. Sí te llega.',
      explicaNoLlega: 'Tienes {total}. El precio es {precio}. No te llega.',
      resolucionNoLlega: 'Eliges algo más barato: {nombre}, por {precio}.',
      paso2Enunciado: 'Paga. El precio es {precio}. Toca tu dinero para ponerlo en el mostrador.',
      hasPuesto: 'En el mostrador: {total}',
      btnPagar: 'Pagar',
      pagoJusto: '¡Pagas justo! No hay cambio. Compra terminada.',
      faltaDinero1: 'Falta dinero. Mira el precio y mira el mostrador.',
      faltaDinero2: 'Faltan {dif}. Pon más dinero en el mostrador.',
      ariaQuitarDelMostrador: 'Quitar {d} del mostrador',
      paso3Enunciado: 'Pagaste {pagado}. El precio es {precio}. Te devuelven esto. ¿Está bien el cambio?',
      pistaPaso3: 'Cuenta el dinero que te han devuelto. Piensa cuánto tenían que devolverte.',
      explicaCambioBien: 'El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está bien.',
      explicaCambioMal: 'El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal.',
      resolucionCambioBien: 'El cambio está bien. ¡Compra terminada!',
      resolucionCambioMal: 'Bien visto: el cambio estaba mal. Se lo dices al dependiente y te da el cambio bueno.',
      btnContinuar: 'Continuar →',
      resumenTienda: 'Compras redondas: {n} de {t}.',
      /* --- ¿Qué me queda? --- */
      enunciadoQuedame: 'Tienes {saldo}. Compras {nombre}. Cuesta {gasto}. ¿Cuánto te queda?',
      pistaQuedame: 'Mira el dinero de la mesa. Quita lo que cuesta y cuenta lo que queda.',
      explicacionQuedameBien: '¡Eso es! Tenías {saldo}. {nombre} cuesta {gasto}. Te quedan {queda}.',
      explicacionQuedameCasi: 'Mira: tenías {saldo}. {nombre} cuesta {gasto}. Te quedan {queda}.',
      resumenQuedame: 'Has calculado bien {n} de {t}.',
      /* --- ¿Mucho o poco? --- */
      enunciadoMucho: '{nombre} cuesta {mostrado}. ¿Está bien de precio o es demasiado?',
      estaBien: 'Está bien',
      esDemasiado: 'Es demasiado',
      pistaMucho: 'Piensa: ¿cuánto cuesta {nombre} normalmente? ¿Mucho más o mucho menos?',
      explicacionMuchoBien: 'Normalmente, {nombre} cuesta unos {ref}. {mostrado} es un precio normal.',
      explicacionMuchoMal: 'Normalmente, {nombre} cuesta unos {ref}. {mostrado} es demasiado dinero.',
      resumenMucho: 'Has pensado bien {n} de {t} precios.'
    },
    en: {
      title: '🏪 The Shop',
      instruccion: 'Here you use money like in real life: you do a whole purchase, keep track of what is left and think about whether a price is fair.',
      volverMenu: '← Menu',
      elegirNivel: 'Choose the level',
      vecesTexto: '{n} times',
      btnOtroNivel: 'Choose another level',
      si: 'Yes',
      no: 'No',
      ariaMesa: 'Money on the table',
      menuTienda: 'One purchase',
      menuTiendaDetalle: 'Start to finish: look, pay and check.',
      menuQuedame: 'What is left?',
      menuQuedameDetalle: 'You keep buying. Work out what is left.',
      menuMucho: 'Too much or okay?',
      menuMuchoDetalle: 'Is that price fair or too much?',
      instruccionTienda: 'You will do a whole purchase: check if you have enough, pay and check the change.',
      instruccionQuedame: 'You start with some money. You buy things. Work out how much is left.',
      instruccionMucho: 'Look at the product and its price. Think if it is fair or too much money.',
      /* --- One purchase (steps) --- */
      compraDe: 'Purchase {n} of {t}',
      paso1Enunciado: '{nombre} costs {precio}. This is your money. Is it enough?',
      pistaPaso1: 'Count your money, slowly. Then look at the price.',
      explicaLlega: 'You have {total}. The price is {precio}. Yes, it is enough.',
      explicaNoLlega: 'You have {total}. The price is {precio}. It is not enough.',
      resolucionNoLlega: 'You choose something cheaper: {nombre}, for {precio}.',
      paso2Enunciado: 'Pay. The price is {precio}. Touch your money to put it on the counter.',
      hasPuesto: 'On the counter: {total}',
      btnPagar: 'Pay',
      pagoJusto: 'You pay the exact amount! No change. Purchase complete.',
      faltaDinero1: 'Not enough money. Look at the price and look at the counter.',
      faltaDinero2: '{dif} missing. Put more money on the counter.',
      ariaQuitarDelMostrador: 'Take {d} off the counter',
      paso3Enunciado: 'You paid {pagado}. The price is {precio}. You get this back. Is the change right?',
      pistaPaso3: 'Count the money you got back. Think how much they had to give you back.',
      explicaCambioBien: 'The right change is {bueno}. You got {mostrado}. It is right.',
      explicaCambioMal: 'The right change is {bueno}. You got {mostrado}. It is wrong.',
      resolucionCambioBien: 'The change is right. Purchase complete!',
      resolucionCambioMal: 'Well spotted: the change was wrong. You tell the shop assistant and they give you the right change.',
      btnContinuar: 'Continue →',
      resumenTienda: 'Perfect purchases: {n} of {t}.',
      /* --- What is left? --- */
      enunciadoQuedame: 'You have {saldo}. You buy {nombre}. It costs {gasto}. How much is left?',
      pistaQuedame: 'Look at the money on the table. Take away the cost and count what is left.',
      explicacionQuedameBien: 'That is it! You had {saldo}. {nombre} costs {gasto}. You have {queda} left.',
      explicacionQuedameCasi: 'Look: you had {saldo}. {nombre} costs {gasto}. You have {queda} left.',
      resumenQuedame: 'You worked it out correctly {n} of {t}.',
      /* --- Too much or okay? --- */
      enunciadoMucho: '{nombre} costs {mostrado}. Is that fair or too much?',
      estaBien: 'It is fair',
      esDemasiado: 'It is too much',
      pistaMucho: 'Think: how much does {nombre} normally cost? Much more or much less?',
      explicacionMuchoBien: 'Normally, {nombre} costs about {ref}. {mostrado} is a normal price.',
      explicacionMuchoMal: 'Normally, {nombre} costs about {ref}. {mostrado} is too much money.',
      resumenMucho: 'You judged {n} of {t} prices correctly.'
    }
  });
})();
