/* ============================================================
   Apptonomia — Constructores (textos ES/EN)
   Claves bloque<Id> con id ASCII capitalizado ('bloqueCesped', no
   'bloqueCésped': el id de bloque también es clase CSS).
   ============================================================ */
App.i18n.register({
  es: {
    title: '🏗️ Constructores',
    instruccion: 'Elige bloques de colores. Toca la zona donde quieres ponerlos. ¡Construye lo que quieras!',
    elegirModo: '¿Qué quieres hacer?',
    modoLibre: '🎨 Crear libremente',
    modoPlantilla: '📋 Seguir un modelo',
    elegirTamano: 'Elige el tamaño del mundo',
    tamPequeno: 'Pequeño',
    tamMediano: 'Mediano',
    tamGrande: 'Grande',
    elegirPlantilla: 'Elige un modelo',
    eligeBloque: 'Elige un bloque',
    bloquesColocados: 'Bloques puestos',
    modoBorrar: '🗑️ Borrar',
    btnLimpiarTodo: '🧹 Empezar de nuevo',
    confirmLimpiar: '¿Seguro? Toca otra vez para borrar todo.',
    btnTerminado: '✔ ¡Listo!',
    finalTitulo: '¡Bravo!',
    btnSeguirCreando: 'Seguir creando',
    btnCambiarPlantilla: 'Cambiar modelo',
    construccionLibre: 'Construcción libre',
    plantillaActiva: 'Modelo: {nombre}',
    pistaPlantilla1: 'Todavía faltan bloques. Fíjate en las casillas con borde de puntos: enseñan el bloque que va en cada una.',
    pistaPlantilla2: 'Las casillas que faltan están marcadas en amarillo. Pon en cada una el bloque de su color.',
    bloqueTierra: 'Bloque de tierra marrón',
    bloquePiedra: 'Bloque de piedra gris',
    bloqueMadera: 'Bloque de madera',
    bloqueAgua: 'Bloque de agua azul',
    bloqueCesped: 'Bloque de césped verde',
    bloqueTecho: 'Bloque de techo rojo',
    bloqueLadrillo: 'Bloque de ladrillo rojo oscuro',
    bloqueArena: 'Bloque de arena',
    celdaVacia: 'Zona vacía para construir',
    celdaConBloque: 'Zona con {bloque}. Toca para cambiar.',
    celdaFantasma: 'Aquí va el {bloque}',
    // Plantillas
    'plantillaCasita': 'Casita',
    'plantillaCastillo': 'Castillo',
    'plantillaPiscina': 'Piscina',
    'plantillaPuente': 'Puente',
    'plantillaCiudad': 'Ciudad',
    'plantillaRio': 'Río con puentes',
    // Resumen final
    resumenLibre: 'Has puesto {n} bloques. ¡Qué bien!',
    resumenPlantilla: 'Has completado el modelo con {n} bloques.'
  },
  en: {
    title: '🏗️ Builders',
    instruccion: 'Choose colored blocks. Tap where you want to place them. Build whatever you want!',
    elegirModo: 'What do you want to do?',
    modoLibre: '🎨 Create freely',
    modoPlantilla: '📋 Follow a model',
    elegirTamano: 'Choose your world size',
    tamPequeno: 'Small',
    tamMediano: 'Medium',
    tamGrande: 'Large',
    elegirPlantilla: 'Choose a model',
    eligeBloque: 'Choose a block',
    bloquesColocados: 'Blocks placed',
    modoBorrar: '🗑️ Erase',
    btnLimpiarTodo: '🧹 Start over',
    confirmLimpiar: 'Sure? Tap again to erase everything.',
    btnTerminado: '✔ Done!',
    finalTitulo: 'Well done!',
    btnSeguirCreando: 'Keep creating',
    btnCambiarPlantilla: 'Change model',
    construccionLibre: 'Free building',
    plantillaActiva: 'Model: {nombre}',
    pistaPlantilla1: 'Some blocks are still missing. Look at the squares with a dotted border: they show which block goes in each one.',
    pistaPlantilla2: 'The missing squares are marked in yellow. Put the matching block in each one.',
    bloqueTierra: 'Brown dirt block',
    bloquePiedra: 'Gray stone block',
    bloqueMadera: 'Wood block',
    bloqueAgua: 'Blue water block',
    bloqueCesped: 'Green grass block',
    bloqueTecho: 'Red roof block',
    bloqueLadrillo: 'Dark red brick block',
    bloqueArena: 'Sand block',
    celdaVacia: 'Empty area to build',
    celdaConBloque: 'Area with {bloque}. Tap to change.',
    celdaFantasma: 'The {bloque} goes here',
    // Plantillas
    'plantillaCasita': 'Little house',
    'plantillaCastillo': 'Castle',
    'plantillaPiscina': 'Pool',
    'plantillaPuente': 'Bridge',
    'plantillaCiudad': 'City',
    'plantillaRio': 'River with bridges',
    // Resumen final
    resumenLibre: 'You placed {n} blocks. Great!',
    resumenPlantilla: 'You completed the model with {n} blocks.'
  }
});
