/* ============================================================
   Apptonomia — Constructores (textos ES/EN)
   ============================================================ */
App.i18n.register({
  es: {
    title: '🏗️ Constructores',
    instruccion: 'Elige bloques de colores. Toca la zona donde quieres ponerlos. ¡Construye lo que quieras!',
    elegirModo: '¿Qué quieres hacer?',
    modoLibre: '🎨 Crear libremente',
    modoPlantilla: '📋 Seguir un modelo',
    elegirPlantilla: 'Elige un modelo',
    eligeBloque: 'Elige un bloque',
    bloquesColocados: 'Bloques puestos',
    modoBorrar: '🗑️ Borrar',
    btnLimpiarTodo: '🧹 Empezar de nuevo',
    btnTerminado: '✔ ¡Listo!',
    finalTitulo: '¡Bravo!',
    btnSeguirCreando: 'Seguir creando',
    btnCambiarPlantilla: 'Cambiar modelo',
    construccionLibre: 'Construcción libre',
    plantillaActiva: 'Modelo: {nombre}',
    confirmLimpiar: '¿Quieres borrar todo y empezar de nuevo?',
    si: 'Sí',
    no: 'No',
    bloqueTierra: 'Bloque de tierra marrón',
    bloquePiedra: 'Bloque de piedra gris',
    bloqueMadera: 'Bloque de madera',
    bloqueAgua: 'Bloque de agua azul',
    bloqueCésped: 'Bloque de césped verde',
    bloqueTecho: 'Bloque de techo rojo',
    bloqueLadrillo: 'Bloque de ladrillo rojo oscuro',
    bloqueArena: 'Bloque de arena',
    celdaVacia: 'Zona vacía para construir',
    celdaConBloque: 'Zona con {bloque}. Toca para cambiar.',
    // Plantillas
    'plantilla.casita': 'Casita',
    'plantilla.castillo': 'Castillo',
    'plantilla.piscina': 'Piscina',
    'plantilla.puente': 'Puente',
    'plantilla.ciudad': 'Ciudad',
    'plantilla.rio': 'Río con puentes',
    // Resumen final
    resumenLibre: 'Has puesto {n} bloques. ¡Qué bien!',
    resumenPlantilla: 'Has completado el modelo con {n} bloques.'
  },
  en: {
    title: '🏗️ Builders',
    instruccion: 'Choose colored blocks. Tap where you want to place them. Build whatever you want!',
    elegirModo: 'What do you want to do?',
    modoLibre: '🎨 Create freely',
    modoPlantilla: '📋 Follow a model',
    elegirPlantilla: 'Choose a model',
    eligeBloque: 'Choose a block',
    bloquesColocados: 'Blocks placed',
    modoBorrar: '🗑️ Erase',
    btnLimpiarTodo: '🧹 Start over',
    btnTerminado: '✔ Done!',
    finalTitulo: 'Well done!',
    btnSeguirCreando: 'Keep creating',
    btnCambiarPlantilla: 'Change model',
    construccionLibre: 'Free building',
    plantillaActiva: 'Model: {nombre}',
    confirmLimpiar: 'Do you want to erase everything and start over?',
    si: 'Yes',
    no: 'No',
    bloqueTierra: 'Brown dirt block',
    bloquePiedra: 'Gray stone block',
    bloqueMadera: 'Wood block',
    bloqueAgua: 'Blue water block',
    bloqueCésped: 'Green grass block',
    bloqueTecho: 'Red roof block',
    bloqueLadrillo: 'Dark red brick block',
    bloqueArena: 'Sand block',
    celdaVacia: 'Empty area to build',
    celdaConBloque: 'Area with {bloque}. Tap to change.',
    // Plantillas
    'plantilla.casita': 'Little house',
    'plantilla.castillo': 'Castle',
    'plantilla.piscina': 'Pool',
    'plantilla.puente': 'Bridge',
    'plantilla.ciudad': 'City',
    'plantilla.rio': 'River with bridges',
    // Resumen final
    resumenLibre: 'You placed {n} blocks. Great!',
    resumenPlantilla: 'You completed the model with {n} blocks.'
  }
});
