/* ============================================================
   Apptonomia — Textos de Teclado (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '⌨️ Teclado',
      textoNombre: '¡Hola! ¿Cómo te llamas? Escribe tu nombre con el teclado.',
      escucharNombreExtra: ' Cuando termines, toca el botón Listo.',
      inputNombreAria: 'Escribe tu nombre',
      btnGuardarNombre: '✅ Listo',
      btnSinNombre: 'Ahora no',
      tipoTecladoAria: 'Tipo de teclado',
      btnSimple: '🔤 Simple',
      btnNormal: '⌨️ Normal',
      btnExtendido: '🔢 Extendido',
      btnMovil: '📱 Móvil',
      btnColoresManos: '🎨 Colores: manos',
      btnColoresDedos: '🎨 Colores: dedos',
      leyendaDedos: 'Cada dedo tiene un color.',
      leyendaManos: 'Azul: mano izquierda. Verde: mano derecha.',
      leyendaMovil: 'Pulgar izquierdo: mitad izquierda. Pulgar derecho: mitad derecha.',
      btnBorrarProgreso: '🗑️ Borrar mi progreso',
      confirmarBorrado: '¿Seguro? Toca otra vez para borrar.',
      avisoBorrado: 'Todo borrado. Empiezas de nuevo.',
      saludoHola: '¡Hola!',
      saludoConNombre: '¡Hola, {nombre}!',
      eligeJuego: 'Elige un juego.',
      modoPosicionNombre: 'Coloca los dedos',
      modoPosicionDetalle: 'Cada dedo tiene su tecla.',
      modoLeccionesNombre: 'Paso a paso',
      modoLeccionesDetalle: 'Aprende las letras en orden.',
      modoPalabrasNombre: 'Palabras',
      modoPalabrasDetalle: 'Escribe palabras y tu nombre.',
      modoTodasNombre: 'Todas las teclas',
      modoTodasDetalle: 'Enciende todas las teclas.',
      modoNumerosNombre: 'Números',
      modoNumerosDetalle: 'Usa el teclado de números.',
      modoLibreNombre: 'Escribe libre',
      modoLibreDetalle: 'Escribe y escucha tu texto.',
      btnMiNombre: '✏️ Mi nombre',
      btnMenu: '← Menú',
      leccionesInstruccion: 'Termina una lección para abrir la siguiente.',
      leccionCerradaAria: 'Lección {n} cerrada. Termina la anterior.',
      tituloJuegoDefault: 'Juego',
      escucharTextoAria: 'Escuchar mi texto',
      borrarTextoAria: 'Borrar el texto',
      areaLibreAria: 'Escribe aquí lo que quieras',
      areaLibrePlaceholder: 'Escribe aquí...',
      noHasEscrito: 'Todavía no has escrito nada.',
      muyBien: '¡Muy bien!',
      muyBienNombre: '¡Muy bien, {nombre}!',
      escribeTuNombre: 'Escribe tu nombre.',
      escribeLaPalabra: 'Escribe la palabra.',
      tituloTodasLasTeclas: 'Todas las teclas',
      instruccionTodasLasTeclas: 'Pulsa todas las teclas de tu teclado. Cada tecla se enciende en la pantalla.',
      deTexto: '{hechas} de {total}',
      escribeAria: 'Escribe: {seq}',
      pulgarTexto: 'Pulgar. La tecla de espacio.',
      manoDedoTexto: 'Mano {mano}. Dedo {dedo}.',
      buscaTecla: 'Busca la tecla en tu teclado.',
      leccionTitulo: 'Lección: {titulo}',
      izquierdaEtiqueta: 'Izquierda',
      derechaEtiqueta: 'Derecha',
      dedo: {
        lp: { mano: 'izquierda', nombre: 'meñique' },
        lr: { mano: 'izquierda', nombre: 'anular' },
        lm: { mano: 'izquierda', nombre: 'medio' },
        li: { mano: 'izquierda', nombre: 'índice' },
        ri: { mano: 'derecha', nombre: 'índice' },
        rm: { mano: 'derecha', nombre: 'medio' },
        rr: { mano: 'derecha', nombre: 'anular' },
        rp: { mano: 'derecha', nombre: 'meñique' },
        th: { mano: 'las dos', nombre: 'pulgar' },
        lt: { mano: 'izquierda', nombre: 'pulgar' },
        rt: { mano: 'derecha', nombre: 'pulgar' }
      },
      teclaLabel: {
        espacio: 'espacio',
        tab: 'Tab',
        mayus: 'Mayús',
        intro: 'Intro',
        borrar: 'Borrar'
      }
    },
    en: {
      title: '⌨️ Keyboard',
      textoNombre: 'Hi! What is your name? Type your name on the keyboard.',
      escucharNombreExtra: ' When you are done, tap the Done button.',
      inputNombreAria: 'Type your name',
      btnGuardarNombre: '✅ Done',
      btnSinNombre: 'Not now',
      tipoTecladoAria: 'Keyboard type',
      btnSimple: '🔤 Simple',
      btnNormal: '⌨️ Normal',
      btnExtendido: '🔢 Extended',
      btnMovil: '📱 Mobile',
      btnColoresManos: '🎨 Colors: hands',
      btnColoresDedos: '🎨 Colors: fingers',
      leyendaDedos: 'Each finger has its own color.',
      leyendaManos: 'Blue: left hand. Green: right hand.',
      leyendaMovil: 'Left thumb: left half. Right thumb: right half.',
      btnBorrarProgreso: '🗑️ Erase my progress',
      confirmarBorrado: 'Are you sure? Tap again to erase.',
      avisoBorrado: 'Everything erased. You start again.',
      saludoHola: 'Hi!',
      saludoConNombre: 'Hi, {nombre}!',
      eligeJuego: 'Choose a game.',
      modoPosicionNombre: 'Place your fingers',
      modoPosicionDetalle: 'Each finger has its key.',
      modoLeccionesNombre: 'Step by step',
      modoLeccionesDetalle: 'Learn the letters in order.',
      modoPalabrasNombre: 'Words',
      modoPalabrasDetalle: 'Type words and your name.',
      modoTodasNombre: 'All the keys',
      modoTodasDetalle: 'Light up every key.',
      modoNumerosNombre: 'Numbers',
      modoNumerosDetalle: 'Use the number pad.',
      modoLibreNombre: 'Free writing',
      modoLibreDetalle: 'Type and listen to your text.',
      btnMiNombre: '✏️ My name',
      btnMenu: '← Menu',
      leccionesInstruccion: 'Finish a lesson to unlock the next one.',
      leccionCerradaAria: 'Lesson {n} locked. Finish the previous one.',
      tituloJuegoDefault: 'Game',
      escucharTextoAria: 'Listen to my text',
      borrarTextoAria: 'Erase the text',
      areaLibreAria: 'Type anything you like here',
      areaLibrePlaceholder: 'Type here...',
      noHasEscrito: 'You have not written anything yet.',
      muyBien: 'Well done!',
      muyBienNombre: 'Well done, {nombre}!',
      escribeTuNombre: 'Type your name.',
      escribeLaPalabra: 'Type the word.',
      tituloTodasLasTeclas: 'All the keys',
      instruccionTodasLasTeclas: 'Press every key on your keyboard. Each key lights up on the screen.',
      deTexto: '{hechas} of {total}',
      escribeAria: 'Type: {seq}',
      pulgarTexto: 'Thumb. The space bar.',
      manoDedoTexto: '{mano} hand. {dedo} finger.',
      buscaTecla: 'Find the key on your keyboard.',
      leccionTitulo: 'Lesson: {titulo}',
      izquierdaEtiqueta: 'Left',
      derechaEtiqueta: 'Right',
      dedo: {
        lp: { mano: 'left', nombre: 'little' },
        lr: { mano: 'left', nombre: 'ring' },
        lm: { mano: 'left', nombre: 'middle' },
        li: { mano: 'left', nombre: 'index' },
        ri: { mano: 'right', nombre: 'index' },
        rm: { mano: 'right', nombre: 'middle' },
        rr: { mano: 'right', nombre: 'ring' },
        rp: { mano: 'right', nombre: 'little' },
        th: { mano: 'both', nombre: 'thumb' },
        lt: { mano: 'left', nombre: 'thumb' },
        rt: { mano: 'right', nombre: 'thumb' }
      },
      teclaLabel: {
        espacio: 'space',
        tab: 'Tab',
        mayus: 'Shift',
        intro: 'Enter',
        borrar: 'Backspace'
      }
    }
  });
})();
