/* ============================================================
   Apptonomia — Textos de El Ajedrez / Chess (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '♟️ El Ajedrez',
      instruccion: 'Aquí practicas dos cosas: primero aprende cómo mueve cada pieza, y después juega una mini partida.',
      volverMenu: '← Menú',
      elegirNivel: 'Elige el nivel',
      veces: 'victorias',
      rondas: 'rondas',
      menuPiezas: 'Las piezas',
      menuPiezasDetalle: 'Aprende cómo mueve cada pieza.',
      menuPartida: 'Mini partida',
      menuPartidaDetalle: 'Juega contra el rival. Captura su rey.',
      /* --- Las piezas (puzzles) --- */
      ariaTableroPiezas: 'Tablero de puzzles',
      puzzleEstado: 'Toca una casilla iluminada. Llega a las estrellas.',
      movimientoTorre: 'La torre ♖ va recto: adelante, atrás y a los lados.',
      movimientoAlfil: 'El alfil ♗ va en diagonal.',
      movimientoDama: 'La dama ♕ va recto y en diagonal.',
      movimientoCaballo: 'El caballo ♘ salta en forma de L.',
      estrellaRecogida: '⭐ ¡Muy bien! Estrella recogida.',
      puzzleCompletado: '🎉 ¡Puzzle completado!',
      resumenPiezas: 'Puzzles completados: {n}.',
      ayudaPuzzle1: 'Mira dónde hay una estrella ⭐. ¿Qué casilla iluminada te acerca a ella?',
      ayudaPuzzle2: 'Toca la casilla marcada: te acerca a la estrella.',
      /* --- Mini partida --- */
      ariaTableroPartida: 'Tablero de ajedrez',
      instruccionPartida: 'Tú llevas las piezas blancas. Captura el rey del rival ♚ y protege el tuyo ♔.',
      teToca: 'Te toca. Toca una de tus piezas.',
      eligeDestino: 'Ahora toca una casilla iluminada.',
      piensaRival: 'El rival piensa…',
      hasCapturado: '¡Bien! Has capturado una pieza del rival.',
      rivalMueve: 'El rival mueve.',
      rivalCome: 'El rival ha capturado una pieza tuya. Tranquilo. Sigue jugando.',
      rivalBloqueado: 'El rival no puede mover ninguna pieza.',
      hasGanado: '🎉 ¡Has capturado el rey! Has ganado.',
      haGanadoRival: 'El rival ha capturado tu rey. ¡Casi! Protege a tu rey con las otras piezas.',
      cerradoGanas: '🎉 No puedes mover, pero tienes más piezas. ¡Has ganado!',
      cerradoEmpate: '🤝 No puedes mover. Tenéis las mismas piezas. ¡Empate! Muy bien jugado.',
      cerradoRival: 'No puedes mover y el rival tiene más piezas. ¡Casi! Otra partida y lo consigues.',
      jugarOtraVez: 'Jugar otra vez',
      btnOtroNivel: 'Elegir otro nivel',
      btnAyuda: '💡 Ayuda',
      ariaEscucharAyuda: 'Escuchar la ayuda',
      ayudaReyRival1: 'Mira el rey del rival ♚. ¿Alguna de tus piezas puede llegar hasta él?',
      ayudaReyRival2: 'Toca la pieza marcada y captura el rey en la casilla marcada: ¡ganas!',
      ayudaSalva1: 'Cuidado: una pieza del rival puede llegar a tu rey ♔. ¿Cómo lo pones a salvo?',
      ayudaSalva2: 'Toca la pieza marcada y muévela a la casilla marcada: así tu rey queda a salvo.',
      ayudaCome1: 'Mira las piezas del rival. ¿Puedes capturar alguna sin peligro?',
      ayudaCome2: 'Toca la pieza marcada y captura en la casilla marcada.',
      ayudaSegura1: 'Antes de mover, piensa: ¿puede el rival capturar tu pieza en esa casilla?',
      ayudaSegura2: 'Toca la pieza marcada y muévela a la casilla marcada: ahí está a salvo.',
      ayudaLibre1: 'Mira tus piezas blancas. ¿Cuál puede moverse?',
      ayudaLibre2: 'Toca la pieza marcada y muévela a la casilla marcada.',
      /* --- Nombres y aria --- */
      piezaTorre: 'torre',
      piezaAlfil: 'alfil',
      piezaDama: 'dama',
      piezaCaballo: 'caballo',
      piezaRey: 'rey',
      tuPieza: 'Tu {p}',
      piezaDelRival: '{p} del rival',
      casillaVacia: 'Casilla vacía',
      casillaEstrella: 'Estrella',
      casillaDestino: 'Puedes mover aquí',
      fila: 'fila {f}, columna {c}'
    },
    en: {
      title: '♟️ Chess',
      instruccion: 'Here you practise two things: first learn how each piece moves, then play a mini match.',
      volverMenu: '← Menu',
      elegirNivel: 'Choose the level',
      veces: 'wins',
      rondas: 'rounds',
      menuPiezas: 'The pieces',
      menuPiezasDetalle: 'Learn how each piece moves.',
      menuPartida: 'Mini match',
      menuPartidaDetalle: "Play against the rival. Capture their king.",
      /* --- The pieces (puzzles) --- */
      ariaTableroPiezas: 'Puzzle board',
      puzzleEstado: 'Touch a highlighted square. Reach the stars.',
      movimientoTorre: 'The rook ♖ moves straight: forwards, backwards and sideways.',
      movimientoAlfil: 'The bishop ♗ moves diagonally.',
      movimientoDama: 'The queen ♕ moves straight and diagonally.',
      movimientoCaballo: 'The knight ♘ jumps in an L shape.',
      estrellaRecogida: '⭐ Well done! Star collected.',
      puzzleCompletado: '🎉 Puzzle complete!',
      resumenPiezas: 'Puzzles completed: {n}.',
      ayudaPuzzle1: 'Look where there is a star ⭐. Which highlighted square takes you closer to it?',
      ayudaPuzzle2: 'Touch the marked square: it takes you closer to the star.',
      /* --- Mini match --- */
      ariaTableroPartida: 'Chess board',
      instruccionPartida: "You play the white pieces. Capture your rival's king ♚ and protect yours ♔.",
      teToca: 'Your turn. Touch one of your pieces.',
      eligeDestino: 'Now touch a highlighted square.',
      piensaRival: 'Your rival is thinking…',
      hasCapturado: "Well done! You captured one of your rival's pieces.",
      rivalMueve: 'Your rival moves.',
      rivalCome: 'Your rival captured one of your pieces. It is okay. Keep playing.',
      rivalBloqueado: 'Your rival cannot move any piece.',
      hasGanado: '🎉 You captured the king! You won.',
      haGanadoRival: 'Your rival captured your king. So close! Protect your king with your other pieces.',
      cerradoGanas: '🎉 You cannot move, but you have more pieces. You won!',
      cerradoEmpate: '🤝 You cannot move. You both have the same pieces. A draw! Very well played.',
      cerradoRival: 'You cannot move and your rival has more pieces. So close! One more game and you will get it.',
      jugarOtraVez: 'Play again',
      btnOtroNivel: 'Choose another level',
      btnAyuda: '💡 Help',
      ariaEscucharAyuda: 'Listen to the help',
      ayudaReyRival1: "Look at your rival's king ♚. Can any of your pieces reach it?",
      ayudaReyRival2: 'Touch the marked piece and capture the king on the marked square: you win!',
      ayudaSalva1: 'Careful: a rival piece can reach your king ♔. How do you keep it safe?',
      ayudaSalva2: 'Touch the marked piece and move it to the marked square: your king stays safe.',
      ayudaCome1: "Look at your rival's pieces. Can you capture one without danger?",
      ayudaCome2: 'Touch the marked piece and capture on the marked square.',
      ayudaSegura1: 'Before you move, think: can your rival capture your piece on that square?',
      ayudaSegura2: 'Touch the marked piece and move it to the marked square: it is safe there.',
      ayudaLibre1: 'Look at your white pieces. Which one can move?',
      ayudaLibre2: 'Touch the marked piece and move it to the marked square.',
      /* --- Names and aria --- */
      piezaTorre: 'rook',
      piezaAlfil: 'bishop',
      piezaDama: 'queen',
      piezaCaballo: 'knight',
      piezaRey: 'king',
      tuPieza: 'Your {p}',
      piezaDelRival: "Rival's {p}",
      casillaVacia: 'Empty square',
      casillaEstrella: 'Star',
      casillaDestino: 'You can move here',
      fila: 'row {f}, column {c}'
    }
  });
})();
