/* ============================================================
   Apptonomia — Textos de Dominó / Dominoes (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '🁵 Dominó',
      instruccion: 'Juega al dominó contra un rival tranquilo. Toca una ficha que encaje con un extremo de la cadena. Si no tienes, roba del montón.',
      instruccionNivel: ' Primero elige el nivel.',
      elegirNivel: 'Elige el nivel',
      veces: 'victorias',
      primeraFicha: 'Pon tu primera ficha. Toca la que quieras.',
      teToca: 'Te toca. La cadena termina en {a} y en {b}.',
      eligeLado: 'Tu ficha encaja en los dos lados. ¿Dónde la pones?',
      ladoIzquierdo: '⬅️ En este lado',
      ladoDerecho: 'En este lado ➡️',
      piensaRival: 'El rival piensa…',
      rivalPone: 'El rival pone una ficha.',
      rivalRoba: 'El rival roba una ficha del montón.',
      rivalPasa: 'El rival no puede poner ficha y pasa.',
      tuPasas: 'No quedan fichas en el montón y no puedes poner. Pasas.',
      hasRobado: 'Has robado una ficha.',
      pistaNoEncaja: '🤔 Esa ficha no encaja. Mira los extremos de la cadena: {a} y {b}.',
      pistaMarcadas: '💡 Las fichas que puedes poner están marcadas.',
      pistaRobar: 'No tienes ninguna ficha que encaje. Pulsa el montón para robar.',
      hasGanado: '🎉 ¡Te has quedado sin fichas! Has ganado.',
      ganaRival: 'El rival se quedó sin fichas. ¡Casi! Otra partida y lo consigues.',
      cerrado: 'Nadie puede poner ficha. Gana quien tiene menos fichas.',
      cerradoGanas: '🎉 La partida se cerró y tú tienes menos fichas. ¡Has ganado!',
      cerradoEmpate: '🤝 La partida se cerró en empate. ¡Muy bien jugado!',
      cerradoRival: 'La partida se cerró y el rival tenía menos fichas. ¡Casi!',
      jugarOtraVez: 'Jugar otra vez',
      btnOtroNivel: 'Elegir otro nivel',
      montonAria: 'Robar una ficha del montón. Quedan {n}.',
      montonVacio: 'El montón está vacío',
      fichaAria: 'Ficha {a} y {b}',
      etiquetaCadena: 'La mesa',
      etiquetaMano: 'Tus fichas',
      fichasRival: 'Fichas del rival: {n}'
    },
    en: {
      title: '🁵 Dominoes',
      instruccion: 'Play dominoes against a relaxed rival. Touch a tile that matches one end of the chain. If you have none, draw from the pile.',
      instruccionNivel: ' First, choose the level.',
      elegirNivel: 'Choose the level',
      veces: 'wins',
      primeraFicha: 'Place your first tile. Touch any one you like.',
      teToca: 'Your turn. The chain ends in {a} and {b}.',
      eligeLado: 'Your tile fits on both sides. Where do you put it?',
      ladoIzquierdo: '⬅️ On this side',
      ladoDerecho: 'On this side ➡️',
      piensaRival: 'Your rival is thinking…',
      rivalPone: 'Your rival places a tile.',
      rivalRoba: 'Your rival draws a tile from the pile.',
      rivalPasa: 'Your rival cannot play and passes.',
      tuPasas: 'The pile is empty and you cannot play. You pass.',
      hasRobado: 'You drew a tile.',
      pistaNoEncaja: '🤔 That tile does not fit. Look at the ends of the chain: {a} and {b}.',
      pistaMarcadas: '💡 The tiles you can play are marked.',
      pistaRobar: 'None of your tiles fit. Touch the pile to draw.',
      hasGanado: '🎉 You have no tiles left! You won.',
      ganaRival: 'Your rival ran out of tiles. So close! One more game and you will get it.',
      cerrado: 'Nobody can play a tile. Whoever has fewer tiles wins.',
      cerradoGanas: '🎉 The game closed and you have fewer tiles. You won!',
      cerradoEmpate: '🤝 The game closed in a draw. Very well played!',
      cerradoRival: 'The game closed and your rival had fewer tiles. So close!',
      jugarOtraVez: 'Play again',
      btnOtroNivel: 'Choose another level',
      montonAria: 'Draw a tile from the pile. {n} left.',
      montonVacio: 'The pile is empty',
      fichaAria: 'Tile {a} and {b}',
      etiquetaCadena: 'The table',
      etiquetaMano: 'Your tiles',
      fichasRival: "Rival's tiles: {n}"
    }
  });
})();
