/* ============================================================
   Apptonomia — Textos de Piano (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '🎹 Piano',
      saludoInicial: '¡Hola, futuro músico! 🎵 ¿Cómo te llamas?',
      escucharAria: 'Escuchar',
      tuNombreAria: 'Tu nombre',
      vamos: '✅ ¡Vamos!',
      menu: '← Menú',
      miNombre: '✏️ Mi nombre',
      saludoMusico: '¡Hola, músico! 🎵',
      saludoConNombre: '¡Hola, {nombre}! 🎵',
      elegirModo: 'Elige cómo quieres tocar 🎶',
      elegirModoTTS: '. Elige cómo quieres tocar.',

      modoLibreNombre: 'Toca libre',
      modoLibreDetalle: 'Explora las notas y crea melodías.',
      modoSeguirNombre: 'Sigue la melodía',
      modoSeguirDetalle: 'Repite la canción que oyes.',
      modoSimonNombre: 'Simón dice',
      modoSimonDetalle: 'Memoriza y repite la secuencia.',
      modoCancionesNombre: 'Canciones',
      modoCancionesDetalle: 'Aprende canciones famosas.',
      modoCompositorNombre: 'Compositor',
      modoCompositorDetalle: 'Crea tu propia canción.',

      explicacionAria: 'Explicación',
      instruccionLibre: '¡Toca las teclas de tu teclado como si fuera un piano! 🎹',
      explicarLibreTTS: 'Toca las teclas de tu teclado: A S D F G H J para las notas blancas, y W E T Y U para las negras. ¡Crea tu propia música!',
      octavaMenosBtn: '◀️ Octava',
      octavaMasBtn: 'Octava ▶️',
      octavaMasTTS: 'Octava más alta',
      octavaMenosTTS: 'Octava más baja',
      grabando: '🔴 Grabando',
      parar: '⏹️ Parar',
      grabandoAviso: '¡Grabando! Toca tus notas.',
      grabadoAviso: '¡Grabado! {n} notas.',
      noTocado: 'No has tocado nada.',
      reproducirGrabacionBtn: '▶️ Escuchar grabación',
      octavaMaxima: 'Ya estás en la octava más aguda.',
      octavaMinima: 'Ya estás en la octava más grave.',

      seguirHeaderTitulo: 'Sigue la melodía',
      instruccionSeguirDefault: 'Escucha la melodía y repítela.',
      instruccionSeguirConNombre: 'Escucha la melodía "{nombre}" y repítela.',
      reproducirMelodiaBtn: '▶️ Reproducir melodía',
      ahoraRepitela: '¡Ahora repítela!',
      perfecto: '¡Perfecto! 🎉',
      casiIntentalo: '¡Casi! Inténtalo de nuevo.',

      simonHeaderTitulo: '🔮 Simón dice',
      instruccionSimon: 'Observa la secuencia y repítela.',
      notaDo: 'Nota Do',
      notaMi: 'Nota Mi',
      notaSol: 'Nota Sol',
      notaSi: 'Nota Si',
      nivelLabel: 'Nivel: {n}',
      puntosLabel: 'Puntos: {n}',
      observaSecuencia: 'Observa la secuencia...',
      tuTurno: '¡Tu turno! Repite la secuencia.',
      correcto: '¡Correcto! 🎉',
      observaSiguiente: 'Observa la siguiente...',
      finJuego: '¡Ups! Fin del juego. Puntos: {n}',

      cancionesHeaderTitulo: 'Canciones',
      elegirCancion: 'Elige una canción para aprender 🎤',
      dificultadFacil: 'Fácil',
      dificultadMedia: 'Media',
      cancionInstruccion: 'Canción: {nombre}. Escucha primero, luego repite.',
      escuchando: 'Escuchando...',
      ahoraTuRepite: '¡Ahora tú! Repite la canción.',
      cancionCumpleanos: '🎂 Cumpleaños',
      cancionEstrellita: '⭐ Estrellita',
      cancionHimnoalegria: '✨ Himno de la alegría',
      cancionVerde: '🌿 Verde',

      compositorHeaderTitulo: '✍️ Compositor',
      crearMelodia: 'Crea tu propia melodía. ¡Sé creativo!',
      placeholderInicial: 'Toca notas para añadir...',
      placeholderVacio: 'Toca notas con el teclado para añadir...',
      reproducirCompBtn: '▶️ Reproducir',
      borrarCompBtn: '🗑️ Borrar',
      guardarCompBtn: '💾 Guardar',
      tusCanciones: '💾 Tus canciones',
      notasCount: '({n} notas)',
      bonitaMelodia: '¡Bonita melodía! 🎵',
      borrado: 'Borrado.',
      tocaNotasPrimero: '¡Toca algunas notas primero!',
      promptNombreCancion: '¿Cómo quieres llamar a tu canción?',
      promptNombreDefault: 'Mi canción',
      nombreCancionAria: 'Nombre de la canción',
      confirmarGuardarBtn: '✅ Guardar',
      cancelarBtn: '❌ Cancelar',
      cancionGuardada: '¡Canción guardada! 🎉',
      cancionBorrada: 'Canción borrada.',

      bienvenidoConNombre: '¡Hola, {nombre}! ¡Bienvenido al piano!',
      escribeNombreTTS: 'Escribe tu nombre para empezar.',

      melodiaAscendente: 'Escala ascendente',
      melodiaDescendente: 'Escala descendente',
      melodiaDoReMi: 'Do Re Mi',
      melodiaArcoiris: 'Arco iris',
      melodiaOndina: 'Ondina',

      nota: {
        C: 'Do', 'C#': 'Do sostenido', D: 'Re', 'D#': 'Re sostenido',
        E: 'Mi', F: 'Fa', 'F#': 'Fa sostenido', G: 'Sol',
        'G#': 'Sol sostenido', A: 'La', 'A#': 'La sostenido', B: 'Si'
      }
    },
    en: {
      title: '🎹 Piano',
      saludoInicial: "Hi, future musician! 🎵 What's your name?",
      escucharAria: 'Listen',
      tuNombreAria: 'Your name',
      vamos: "✅ Let's go!",
      menu: '← Menu',
      miNombre: '✏️ My name',
      saludoMusico: 'Hi, musician! 🎵',
      saludoConNombre: 'Hi, {nombre}! 🎵',
      elegirModo: 'Choose how you want to play 🎶',
      elegirModoTTS: '. Choose how you want to play.',

      modoLibreNombre: 'Free play',
      modoLibreDetalle: 'Explore the notes and make tunes.',
      modoSeguirNombre: 'Follow the tune',
      modoSeguirDetalle: 'Repeat the song you hear.',
      modoSimonNombre: 'Simon Says',
      modoSimonDetalle: 'Remember and repeat the pattern.',
      modoCancionesNombre: 'Songs',
      modoCancionesDetalle: 'Learn well-known songs.',
      modoCompositorNombre: 'Composer',
      modoCompositorDetalle: 'Create your own song.',

      explicacionAria: 'Explanation',
      instruccionLibre: 'Press the keys on your keyboard like a piano! 🎹',
      explicarLibreTTS: 'Press the keys on your keyboard. Use A S D F G H J for the white notes, and W E T Y U for the black notes. Make your own music!',
      octavaMenosBtn: '◀️ Octave',
      octavaMasBtn: 'Octave ▶️',
      octavaMasTTS: 'Higher octave',
      octavaMenosTTS: 'Lower octave',
      grabando: '🔴 Recording',
      parar: '⏹️ Stop',
      grabandoAviso: 'Recording! Play your notes.',
      grabadoAviso: 'Recorded! {n} notes.',
      noTocado: "You haven't played anything.",
      reproducirGrabacionBtn: '▶️ Listen to recording',
      octavaMaxima: "You are already in the highest octave.",
      octavaMinima: "You are already in the lowest octave.",

      seguirHeaderTitulo: 'Follow the tune',
      instruccionSeguirDefault: 'Listen to the tune and repeat it.',
      instruccionSeguirConNombre: 'Listen to "{nombre}" and repeat it.',
      reproducirMelodiaBtn: '▶️ Play the tune',
      ahoraRepitela: 'Now repeat it!',
      perfecto: 'Perfect! 🎉',
      casiIntentalo: 'Almost! Try again.',

      simonHeaderTitulo: '🔮 Simon Says',
      instruccionSimon: 'Watch the pattern and repeat it.',
      notaDo: 'Note C',
      notaMi: 'Note E',
      notaSol: 'Note G',
      notaSi: 'Note B',
      nivelLabel: 'Level: {n}',
      puntosLabel: 'Points: {n}',
      observaSecuencia: 'Watch the pattern...',
      tuTurno: 'Your turn! Repeat the pattern.',
      correcto: 'Correct! 🎉',
      observaSiguiente: 'Watch the next one...',
      finJuego: 'Oops! Game over. Points: {n}',

      cancionesHeaderTitulo: 'Songs',
      elegirCancion: 'Choose a song to learn 🎤',
      dificultadFacil: 'Easy',
      dificultadMedia: 'Medium',
      cancionInstruccion: 'Song: {nombre}. Listen first, then repeat.',
      escuchando: 'Listening...',
      ahoraTuRepite: 'Now you! Repeat the song.',
      cancionCumpleanos: '🎂 Happy Birthday',
      cancionEstrellita: '⭐ Twinkle Twinkle',
      cancionHimnoalegria: '✨ Ode to Joy',
      cancionVerde: '🌿 Green',

      compositorHeaderTitulo: '✍️ Composer',
      crearMelodia: 'Create your own tune. Be creative!',
      placeholderInicial: 'Play notes to add them...',
      placeholderVacio: 'Play notes on the keyboard to add them...',
      reproducirCompBtn: '▶️ Play',
      borrarCompBtn: '🗑️ Delete',
      guardarCompBtn: '💾 Save',
      tusCanciones: '💾 Your songs',
      notasCount: '({n} notes)',
      bonitaMelodia: 'Lovely tune! 🎵',
      borrado: 'Deleted.',
      tocaNotasPrimero: 'Play some notes first!',
      promptNombreCancion: 'What do you want to call your song?',
      promptNombreDefault: 'My song',
      nombreCancionAria: 'Song name',
      confirmarGuardarBtn: '✅ Save',
      cancelarBtn: '❌ Cancel',
      cancionGuardada: 'Song saved! 🎉',
      cancionBorrada: 'Song deleted.',

      bienvenidoConNombre: 'Hi, {nombre}! Welcome to the piano!',
      escribeNombreTTS: 'Type your name to start.',

      melodiaAscendente: 'Going up',
      melodiaDescendente: 'Going down',
      melodiaDoReMi: 'Do Re Mi',
      melodiaArcoiris: 'Rainbow',
      melodiaOndina: 'Water song',

      nota: {
        C: 'C', 'C#': 'C sharp', D: 'D', 'D#': 'D sharp',
        E: 'E', F: 'F', 'F#': 'F sharp', G: 'G',
        'G#': 'G sharp', A: 'A', 'A#': 'A sharp', B: 'B'
      }
    }
  });
})();
