#!/usr/bin/env node
/* ============================================================
   Apptonomia suite — build-head.js
   Generates the SEO/OG/Twitter head block of a sibling project
   from its app.config.json. Idempotent: replaces the block
   delimited by <!-- build:head:start --> / <!-- build:head:end -->
   in the target HTML. Leaves JSON-LD, favicons, scripts and
   stylesheets untouched (each project keeps its own).

   Usage:
     node scripts/build-head.js                         # builds the landing (apptonomia itself)
     node scripts/build-head.js ../calculia             # builds calculia/site/index.html
     node scripts/build-head.js ../calculia --entry site/index.html
     node scripts/build-head.js ../teclatlon --check    # dry-run: prints diff, exits 0 if no diff

   Why this exists:
     - The 6 apps had divergent <head> blocks (Routime had
       alternateName, Teclatlon had operatingSystem tweaks,
       Okeymoney had a different og:site_name); keeping them
       in sync by hand was a known footgun.
     - app.config.json is the single source of truth: name,
       domain, title, description, keywords, og:site_name,
       og:description, og:image alt, theme-color, etc.
     - JSON-LD stays out of scope: each app has its own block
       (applicationCategory varies: EducationalApplication,
       FinanceApplication; Routime has alternateName; Apptonomia
       has the full ItemList of 6 products). Formalising that
       would have required a per-app profile anyway.

   What the generated block does NOT do:
     - It does NOT switch og:image to .svg: the meta still
       points to og-image.svg as a temporary placeholder until
       a designer exports the real 1200x630 PNG. SVG is not
       supported by Open Graph / Twitter card crawlers (per
       ogp.me), so previews will be missing until the PNG is
       added. The SVG file itself carries a prominent
       PLACEHOLDER comment for that reason.

   Exit codes:
     0  success (or --check with no diff)
     1  validation error / missing file / --check with diff
   ============================================================ */

'use strict';

var fs = require('fs');
var path = require('path');

var MARKER_START = '<!-- build:head:start -->';
var MARKER_END = '<!-- build:head:end -->';

function fail(msg, code) {
  console.error('ERROR: ' + msg);
  process.exit(code || 1);
}

function readJSON(p) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch (e) {
    fail('cannot read ' + p + ': ' + e.message);
  }
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildHead(cfg, opts) {
  var indent = (opts && opts.indent) || '';
  var isSuiteLanding = !!cfg.hasItemList;
  var author = escapeHtml(cfg.author || cfg.name);
  var siteName = escapeHtml(cfg.ogSiteName || cfg.name);
  var domain = cfg.domain;

  var lines = [];
  lines.push(MARKER_START);
  lines.push('');
  lines.push('  <!-- ===== SEO: title, description, keywords, canonical, robots =====');
  lines.push('       Generated by scripts/build-head.js from ' + (opts.configRel || 'app.config.json') + '.');
  lines.push('       Do NOT edit the block between build:head:start and build:head:end');
  lines.push('       by hand -- it will be overwritten. Edit the config and re-run. -->');
  lines.push('  <title>' + escapeHtml(cfg.title) + '</title>');
  lines.push('  <meta name="description" content="' + escapeHtml(cfg.description) + '">');
  lines.push('  <meta name="keywords" content="' + escapeHtml(cfg.keywords) + '">');
  lines.push('  <meta name="author" content="' + author + '">');
  lines.push('  <meta name="robots" content="index,follow,max-image-preview:large">');
  lines.push('  <link rel="canonical" href="https://' + domain + '/">');
  lines.push('  <link rel="alternate" hreflang="es" href="https://' + domain + '/?lang=es">');
  lines.push('  <link rel="alternate" hreflang="en" href="https://' + domain + '/?lang=en">');
  lines.push('  <link rel="alternate" hreflang="x-default" href="https://' + domain + '/">');
  lines.push('');
  lines.push('  <!-- ===== Open Graph (Facebook, LinkedIn, Discord, WhatsApp previews) =====');
  if (isSuiteLanding) {
    lines.push('       Apptonomia is the suite gateway; its OG block is the broadest');
    lines.push('       (one ItemList with the 6 siblings in JSON-LD, see below). -->');
  } else {
    lines.push('       og:image currently points to og-image.svg as a placeholder.');
    lines.push('       Open Graph does NOT support SVG -- replace with a real');
    lines.push('       1200x630 PNG (og-image.png) before public deploy for');
    lines.push('       WhatsApp / LinkedIn / Twitter previews to render. -->');
  }
  lines.push('  <meta property="og:type" content="website">');
  lines.push('  <meta property="og:site_name" content="' + siteName + '">');
  lines.push('  <meta property="og:locale" content="es_ES">');
  lines.push('  <meta property="og:locale:alternate" content="en_US">');
  lines.push('  <meta property="og:title" content="' + escapeHtml(cfg.title) + '">');
  lines.push('  <meta property="og:description" content="' + escapeHtml(cfg.ogDescription) + '">');
  lines.push('  <meta property="og:url" content="https://' + domain + '/">');
  lines.push('  <meta property="og:image" content="https://' + domain + '/og-image.svg">');
  lines.push('  <meta property="og:image:width" content="1200">');
  lines.push('  <meta property="og:image:height" content="630">');
  lines.push('  <meta property="og:image:alt" content="' + escapeHtml(cfg.ogImageAlt) + '">');
  lines.push('');
  lines.push('  <!-- ===== Twitter Card ===== -->');
  lines.push('  <meta name="twitter:card" content="summary_large_image">');
  lines.push('  <meta name="twitter:title" content="' + escapeHtml(cfg.title) + '">');
  lines.push('  <meta name="twitter:description" content="' + escapeHtml(cfg.twitterDescription) + '">');
  lines.push('  <meta name="twitter:image" content="https://' + domain + '/og-image.svg">');
  lines.push('');
  lines.push('  <!-- ===== Theme / appearance ===== -->');
  lines.push('  <meta name="theme-color" content="' + escapeHtml(cfg.themeColor || '#FAF7F2') + '">');
  lines.push('  <meta name="color-scheme" content="' + escapeHtml(cfg.colorScheme || 'light') + '">');
  lines.push('');
  lines.push(MARKER_END);
  return lines.map(function (l) { return indent + l; }).join('\n');
}

function findExistingBlock(html) {
  var startIdx = html.indexOf(MARKER_START);
  var endIdx = html.indexOf(MARKER_END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return null;
  // Include trailing newline if present so we leave the surrounding spacing clean.
  var after = endIdx + MARKER_END.length;
  if (html.charAt(after) === '\n') after += 1;
  return { start: startIdx, end: after, hasMarkers: true };
}

function insertBlock(html, indent, configRel, cfg) {
  // No markers yet: find the existing SEO region and replace it in-place.
  // The SEO region is everything between the opening of <head> (or <meta charset>)
  // and the first non-SEO tag (JSON-LD <script>, <link rel="stylesheet">,
  // <link rel="icon">, <link rel="manifest">, <link rel="apple-touch-icon">,
  // <script> bootstrap, or </head>). We also strip any comments in that range
  // — the build-head block itself ends with the closing marker which we own.
  var headOpen = html.indexOf('<head>');
  if (headOpen === -1) fail('cannot find <head> in target HTML');
  var insertAt = headOpen + '<head>'.length;
  // Skip the newline right after <head> so the block sits cleanly.
  if (html.charAt(insertAt) === '\n') insertAt += 1;

  // Find where the SEO block ends. Scan forward from insertAt for the first
  // "non-SEO" marker.
  var STOP_PATTERNS = [
    '<script type="application/ld+json"',
    '<link rel="stylesheet"',
    '<link rel="icon"',
    '<link rel="manifest"',
    '<link rel="apple-touch-icon"',
    '<link rel="canonical"', // keep canonical AFTER our block to avoid duplicating; we move it into the block
    '<script src="',
    '<script>window',
    '<style',
    '</head>'
  ];
  var endIdx = -1;
  for (var i = 0; i < STOP_PATTERNS.length; i++) {
    var p = STOP_PATTERNS[i];
    var idx = html.indexOf(p, insertAt);
    if (idx !== -1 && (endIdx === -1 || idx < endIdx)) endIdx = idx;
  }
  if (endIdx === -1) fail('cannot find the end of the SEO region in target HTML');

  var block = buildHead(cfg, { indent: indent, configRel: configRel });
  // Trim trailing whitespace from the SEO region so we don't double-space.
  while (endIdx > insertAt && /\s/.test(html.charAt(endIdx - 1))) endIdx -= 1;
  return html.slice(0, insertAt) + '\n  ' + block + '\n  ' + html.slice(endIdx);
}

function replaceBlock(html, indent, configRel, cfg) {
  var span = findExistingBlock(html);
  if (!span) return null;
  var block = buildHead(cfg, { indent: indent, configRel: configRel });
  return html.slice(0, span.start) + block + html.slice(span.end);
}

/* --- One-shot migration: strip the existing SEO region in <head> and
   insert a build:head block in its place. Used by `--init`. The SEO region
   is everything from the first <meta charset> up to (but not including) the
   first non-SEO tag — see insertBlock() above for the comment on why this
   is fragile. We detect the boundaries by anchor markers that appear in
   every sibling's <head> today: <meta charset> as the start, and either
   <script type="application/ld+json"> or </head> as the end. */
function migrateBlock(html, cfg) {
  var headOpen = html.indexOf('<head>');
  if (headOpen === -1) fail('cannot find <head> in target HTML');
  var anchorStart = html.indexOf('<meta charset=', headOpen);
  if (anchorStart === -1) fail('cannot find <meta charset= in target HTML');
  // Walk back to the start of the line so we keep the original indentation.
  var lineStart = html.lastIndexOf('\n', anchorStart) + 1;

  var anchorEnd = html.indexOf('<script type="application/ld+json"', headOpen);
  if (anchorEnd === -1) anchorEnd = html.indexOf('</head>', headOpen);
  if (anchorEnd === -1) fail('cannot find a JSON-LD block or </head> in target HTML');
  // Walk the end back to the previous newline so we delete the whole SEO region.
  var endOfRegion = html.lastIndexOf('\n', anchorEnd);
  if (endOfRegion === -1) fail('cannot compute end of SEO region');

  var indent = (html.slice(lineStart, anchorStart).match(/^[ \t]*/) || ['  '])[0];
  var block = buildHead(cfg, { indent: indent, configRel: 'app.config.json' });
  return html.slice(0, lineStart) + block + '\n\n  ' + html.slice(endOfRegion + 1);
}

function detectIndent(html, anchorIdx) {
  // Look at the line containing `anchorIdx`; report the leading whitespace up to
  // the first non-space char. Falls back to two spaces (the historical convention).
  var lineStart = html.lastIndexOf('\n', anchorIdx) + 1;
  var m = html.slice(lineStart, anchorIdx).match(/^[ \t]*/);
  return m ? m[0] : '  ';
}

function main() {
  var argv = process.argv.slice(2);
  if (argv.indexOf('--help') !== -1 || argv.indexOf('-h') !== -1) {
    console.log(fs.readFileSync(__filename, 'utf8').split('\n').slice(2, 36).map(function (l) { return l.replace(/^      /, ''); }).join('\n'));
    process.exit(0);
  }

  var checkOnly = argv.indexOf('--check') !== -1;
  var initMode = argv.indexOf('--init') !== -1;
  var entryIdx = argv.indexOf('--entry');
  // Default entry is site/index.html (multi-activity siblings); apptonomia
  // (the suite gateway) and single-activity siblings use index.html. We try
  // site/index.html first and fall back to index.html when --entry is not set.
  var entryRel = entryIdx !== -1 ? argv[entryIdx + 1] : null;
  var siblingArg = argv.find(function (a, i) {
    return i !== entryIdx && i !== entryIdx + 1 && a !== '--check' && !a.startsWith('--');
  });

  var here = __dirname;
  // here is apptonomia/scripts by default. The Miralante suite root lives
  // one level above apptonomia (../.. from this file). All sibling paths
  // passed on the CLI are resolved against the suite root so that
  // `node scripts/build-head.js --check ../calculia` works from apptonomia/.
  var suiteRoot = path.resolve(here, '..', '..');
  var siblingDir = siblingArg ? path.resolve(suiteRoot, siblingArg) : path.resolve(here, '..');
  var configPath = path.join(siblingDir, 'app.config.json');
  var targetPath;
  if (entryRel) {
    targetPath = path.join(siblingDir, entryRel);
  } else {
    var siteCandidate = path.join(siblingDir, 'site', 'index.html');
    targetPath = fs.existsSync(siteCandidate) ? siteCandidate : path.join(siblingDir, 'index.html');
  }

  if (!fs.existsSync(configPath)) fail('config not found: ' + configPath);
  if (!fs.existsSync(targetPath)) fail('target HTML not found: ' + targetPath);

  var cfg = readJSON(configPath);
  if (!cfg.domain || !cfg.title) fail('app.config.json missing required fields: domain, title');
  if (!cfg.ogDescription || !cfg.twitterDescription) fail('app.config.json missing required fields: ogDescription, twitterDescription');

  var html = fs.readFileSync(targetPath, 'utf8');
  var anchorIdx = html.indexOf('<title>');
  if (anchorIdx === -1) anchorIdx = html.indexOf('<meta name="description"');
  if (anchorIdx === -1) fail('cannot find a title or description anchor to detect indent');
  var indent = detectIndent(html, anchorIdx);

  var configRel = path.relative(path.dirname(targetPath), configPath).replace(/\\/g, '/');

  var next;
  if (initMode) {
    if (findExistingBlock(html)) fail('--init cannot run on a file that already has build:head markers; remove them first or run without --init.');
    next = migrateBlock(html, cfg);
  } else if (findExistingBlock(html)) {
    next = replaceBlock(html, indent, configRel, cfg);
  } else {
    next = insertBlock(html, indent, configRel, cfg);
  }
  if (next === null) fail('failed to compute the next HTML content');

  if (checkOnly) {
    if (next === html) {
      console.log('OK: ' + path.relative(process.cwd(), targetPath) + ' is up to date.');
      process.exit(0);
    }
    console.error('DIFF: ' + path.relative(process.cwd(), targetPath) + ' is out of date; run without --check to update.');
    process.exit(1);
  }

  fs.writeFileSync(targetPath, next, 'utf8');
  console.log('wrote ' + path.relative(process.cwd(), targetPath) + ' (' + cfg.name + ')');
}

main();
