/* ============================================================
   Apptonomia — Textos de Las Damas / Checkers (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '🔴 Las Damas',
      instruccion: 'Tú llevas las fichas rojas 🔴. Las fichas van en diagonal. Salta por encima de una ficha azul para comerla. Si llegas al final, tu ficha se convierte en dama 👑.',
      instruccionNivel: ' Primero elige el nivel.',
      elegirNivel: 'Elige el nivel',
      veces: 'victorias',
      ariaTablero: 'Tablero de damas',
      teToca: 'Te toca. Toca una de tus fichas rojas.',
      eligeDestino: 'Ahora toca una casilla iluminada.',
      piensaRival: 'El rival piensa…',
      hasComido: '¡Bien! Has saltado y comido una ficha azul.',
      rivalMueve: 'El rival mueve una ficha.',
      rivalCome: 'El rival ha comido una ficha tuya. Tranquilo. Sigue jugando.',
      coronaTuya: '👑 ¡Tu ficha ya es dama! Ahora también puede ir hacia atrás.',
      coronaRival: 'Una ficha del rival ya es dama 👑.',
      rivalBloqueado: 'El rival no puede mover ninguna ficha.',
      hasGanado: '🎉 ¡Has ganado! Muy bien jugado.',
      haGanadoRival: 'El rival ha ganado esta vez. ¡Casi! Antes de mover, mira si el rival puede saltar sobre tu ficha.',
      cerradoGanas: '🎉 No puedes mover, pero tienes más fichas. ¡Has ganado!',
      cerradoEmpate: '🤝 No puedes mover. Tenéis las mismas fichas. ¡Empate! Muy bien jugado.',
      cerradoRival: 'No puedes mover y el rival tiene más fichas. ¡Casi! Otra partida y lo consigues.',
      jugarOtraVez: 'Jugar otra vez',
      btnOtroNivel: 'Elegir otro nivel',
      btnAyuda: '💡 Ayuda',
      ariaEscucharAyuda: 'Escuchar la ayuda',
      casillaVacia: 'Casilla vacía',
      casillaTuya: 'Tu ficha',
      casillaDama: 'Tu dama',
      casillaRival: 'Ficha del rival',
      casillaDamaRival: 'Dama del rival',
      casillaDestino: 'Puedes mover aquí',
      fila: 'fila {f}, columna {c}',
      ayudaCome1: 'Mira las fichas azules. ¿Hay alguna con una casilla vacía justo detrás, en diagonal?',
      ayudaCome2: 'Toca la ficha marcada y salta a la casilla marcada: te comes la ficha azul.',
      ayudaSegura1: 'Antes de mover, piensa: ¿puede el rival saltar sobre tu ficha en esa casilla?',
      ayudaSegura2: 'Toca la ficha marcada y muévela a la casilla marcada: ahí el rival no puede comerla.',
      ayudaLibre1: 'Mira tus fichas rojas. ¿Cuál puede avanzar en diagonal?',
      ayudaLibre2: 'Toca la ficha marcada y muévela a la casilla marcada para avanzar.'
    },
    en: {
      title: '🔴 Checkers',
      instruccion: 'You play the red pieces 🔴. Pieces move diagonally. Jump over a blue piece to capture it. If you reach the far end, your piece becomes a king 👑.',
      instruccionNivel: ' First, choose the level.',
      elegirNivel: 'Choose the level',
      veces: 'wins',
      ariaTablero: 'Checkers board',
      teToca: 'Your turn. Touch one of your red pieces.',
      eligeDestino: 'Now touch a highlighted square.',
      piensaRival: 'Your rival is thinking…',
      hasComido: 'Well done! You jumped and captured a blue piece.',
      rivalMueve: 'Your rival moves a piece.',
      rivalCome: 'Your rival captured one of your pieces. It is okay. Keep playing.',
      coronaTuya: '👑 Your piece is now a king! It can also move backwards.',
      coronaRival: "One of your rival's pieces is now a king 👑.",
      rivalBloqueado: 'Your rival cannot move any piece.',
      hasGanado: '🎉 You won! Very well played.',
      haGanadoRival: 'Your rival won this time. So close! Before you move, check if your rival can jump over your piece.',
      cerradoGanas: '🎉 You cannot move, but you have more pieces. You won!',
      cerradoEmpate: '🤝 You cannot move. You both have the same pieces. A draw! Very well played.',
      cerradoRival: 'You cannot move and your rival has more pieces. So close! One more game and you will get it.',
      jugarOtraVez: 'Play again',
      btnOtroNivel: 'Choose another level',
      btnAyuda: '💡 Help',
      ariaEscucharAyuda: 'Listen to the help',
      casillaVacia: 'Empty square',
      casillaTuya: 'Your piece',
      casillaDama: 'Your king',
      casillaRival: "Rival's piece",
      casillaDamaRival: "Rival's king",
      casillaDestino: 'You can move here',
      fila: 'row {f}, column {c}',
      ayudaCome1: 'Look at the blue pieces. Is there one with an empty square just behind it, diagonally?',
      ayudaCome2: 'Touch the marked piece and jump to the marked square: you capture the blue piece.',
      ayudaSegura1: 'Before you move, think: can your rival jump over your piece on that square?',
      ayudaSegura2: 'Touch the marked piece and move it to the marked square: your rival cannot capture it there.',
      ayudaLibre1: 'Look at your red pieces. Which one can move forward diagonally?',
      ayudaLibre2: 'Touch the marked piece and move it to the marked square to advance.'
    }
  });
})();
