/* ============================================================
   Apptonomia — Textos de Los Números (ES/EN)
   Se registran en App.i18n con App.i18n.register(). Ver assets/js/i18n.js.
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    es: {
      title: '🧮 Los Números',
      instruccionMenu: 'Matemáticas para el día a día. Elige una actividad.',
      notaMonedero: '💶 Para pagar con monedas, entra en {link}.',
      notaMonederoLink: 'El Monedero',
      btnVolverMenu: '← Otras actividades',
      otroNivel: 'Elegir otro nivel',
      instruccionExtra: ' Primero elige el nivel.',
      veces: '{n} veces',
      resumenFinal: 'Has resuelto {n} preguntas de {actividad}. Ahora tienes {estrellas} estrellas.',
      btnMasDificil: '¿Quieres probar «{nombre}»?',
      btnOtraActividad: 'Otra actividad',
      explicacionCorrecta: '✅ ¡Correcto! La respuesta es: ',
      explicacionIncorrectaA: '❌ No es esa. La respuesta correcta es: ',
      pista: '🤔 Prueba otra vez. Piensa con calma.',
      grupoEtq: { 0: '', 1: 'miles', 2: 'millones', 3: 'miles de millones', 4: 'billones' },
      leyendaUnidadesTxt: 'unidades',
      leyendaDecenasTxt: 'decenas',
      leyendaCentenasTxt: 'centenas',
      leyendaEurosTxt: 'euros',
      leyendaComaTxt: 'la coma y los céntimos',
      leyendaPartesPintadasTxt: 'partes pintadas',
      leyendaPartesTotalTxt: 'partes en total',
      euroUno: '1 euro',
      euroVarios: '{e} euros',
      precioConCentimos: '{euros} y {c} céntimos',
      centenaSingular: 'centena', centenaPlural: 'centenas',
      decenaSingular: 'decena', decenaPlural: 'decenas',
      unidadSingular: 'unidad', unidadPlural: 'unidades',
      grupo: {
        numeros: 'Los números',
        calcular: 'Calcular y medir'
      },
      actividad: {
        contar: { nombre: 'Contar', detalle: 'Sigue la serie.', instruccion: 'Mira los números. Piensa qué número sigue. Toca ese número.' },
        unidades: { nombre: 'Unidades y decenas', detalle: '¿Qué número es?', instruccion: 'Cada color ayuda a leer el número. Azul: unidades. Verde: decenas. Morado: centenas.' },
        fracciones: { nombre: 'Fracciones', detalle: 'Las partes de algo.', instruccion: 'Una fracción es una parte de algo. Mira las partes pintadas de la figura.' },
        decimales: { nombre: 'Decimales', detalle: 'Los euros y la coma.', instruccion: 'La coma separa los euros y los céntimos. Delante van los euros. Detrás van los céntimos.' },
        sumar: { nombre: 'Sumar', detalle: 'Las tablas de sumar.', instruccion: 'Cuenta los puntos de colores. Toca el resultado.' },
        restar: { nombre: 'Restar', detalle: 'Las tablas de restar.', instruccion: 'Restar es quitar. Cuenta los puntos que no tienen una cruz.' },
        multiplicar: { nombre: 'Multiplicar', detalle: 'Las tablas de multiplicar.', instruccion: 'Multiplicar es sumar grupos iguales. Cuenta las filas de puntos.' },
        cabeza: { nombre: 'De cabeza', detalle: 'Calcula sin papel.', instruccion: 'Piensa el resultado de cabeza. Fíjate en la cifra que cambia.' },
        llega: { nombre: '¿Te llega?', detalle: '¿Tienes bastante dinero?', instruccion: 'Mira cuánto dinero tienes. Mira cuánto cuesta. Piensa si te llega o si te falta.' },
        cambio: { nombre: 'El Cambio', detalle: '¿Cuánto te devuelven?', instruccion: 'Pagas con un billete. Te devuelven lo que sobra. Calcula cuánto te devuelven.' },
        medidas: { nombre: 'Medidas', detalle: 'Metros, kilos y litros.', instruccion: 'Piensa cuánto es cada medida. Toca la respuesta.' }
      },
      nivel: {
        c1: 'De 1 en 1', c2: 'De 2 en 2', c5: 'De 5 en 5', c10: 'De 10 en 10',
        u99: 'Hasta 99', u999: 'Hasta 999', umiles: 'Los miles', umillones: 'Millones y billón', udictado: 'Escucha y elige',
        f1: 'Mitades y cuartos', f2: 'Tercios y sextos', f3: '¿Cuál es más grande?',
        d1: 'Leer precios', d2: '¿Qué cuesta más?',
        s10: 'Sumas hasta 10', s20: 'Sumas hasta 20',
        r10: 'Restas hasta 10', r20: 'Restas hasta 20',
        m1: 'Tablas del 2, 5 y 10', m2: 'Tablas del 3 y 4', m3: 'Tablas del 6 y 7', m4: 'Tablas del 8 y 9',
        k1: 'Dobles', k2: 'Sumar 10', k3: 'Sumar 100', k4: 'Sumar 1.000',
        k5: 'Restar 10', k6: 'Restar 100', k7: 'Restar 1.000',
        k8: 'Multiplicar x10', k9: 'Multiplicar x100',
        ll1: 'Un producto', ll2: 'Dos productos',
        ca1: 'Cambio fácil', ca2: 'Cambio con céntimos',
        me1: 'Longitud: metros', me2: 'Peso: kilos', me3: 'Capacidad: litros'
      },
      producto: {
        pan: 'el pan', leche: 'la leche', zumo: 'el zumo', manzanas: 'las manzanas',
        queso: 'el queso', galletas: 'las galletas', lapiz: 'el lápiz', cuaderno: 'el cuaderno'
      },
      gen: {
        contarEnunciado: '¿Qué número sigue?',
        contarHablar: 'Cuenta de {paso} en {paso}. {seq}. ¿Qué número sigue?',
        bloquesEnunciado: '¿Qué número forman los bloques?',
        bloquesHablar: '¿Qué número forman los bloques? Hay {texto}.',
        bloquesVisualAria: 'Bloques: {texto}',
        lecturaEnunciadoNumASim: '¿Cómo se lee este número?',
        lecturaHablarNumASim: '¿Cómo se lee este número? Las etiquetas de abajo te ayudan.',
        lecturaEnunciadoSimANum: '¿Qué número es?',
        lecturaHablarSimANum: '{palabras}. ¿Qué número es?',
        dictadoEnunciado: 'Escucha el número. Después, tócalo.',
        dictadoVisualAria: 'Escucha el número con el botón de audio.',
        sumarEnunciado: '¿Cuánto es {a} + {b}?',
        sumarHablar: '¿Cuánto es {a} más {b}? Cuenta los puntos.',
        restarEnunciado: '¿Cuánto es {a} − {b}?',
        restarHablar: '¿Cuánto es {a} menos {b}? Cuenta los puntos que no tienen una cruz.',
        restarPista: 'Quita {b}. Cuenta los puntos que quedan.',
        multiplicarEnunciado: '¿Cuánto es {a} × {b}?',
        multiplicarHablar: '¿Cuánto es {a} por {b}? Mira: {a} filas con {b} puntos cada una.',
        multiplicarPista: '{a} filas. Cada fila tiene {b} puntos.',
        doblesEnunciado: '¿Cuánto es {a} + {a}?',
        doblesHablar: '¿Cuánto es {a} más {a}? Los dos números son iguales. Es un doble.',
        doblesPista: 'Los dos números son iguales. Es un doble.',
        pistaDecenas: 'Solo cambia la cifra verde: las decenas.',
        pistaCentenas: 'Solo cambia la cifra morada: las centenas.',
        pistaMiles: 'Solo cambia la cifra de los miles.',
        sumaGrandeEnunciado: '¿Cuánto es {n} + {suma}?',
        sumaGrandeHablar: '¿Cuánto es {n} más {suma}? {pista}',
        restaGrandeEnunciado: '¿Cuánto es {n} − {resta}?',
        restaGrandeHablar: '¿Cuánto es {n} menos {resta}? {pista}',
        multiplicaGrandeEnunciado: '¿Cuánto es {n} × {factor}?',
        multiplicaGrandeHablar: '¿Cuánto es {n} por {factor}? Añade {ceros} al final.',
        multiplicaGrandePista: 'Añade {ceros} al final de {n}.',
        cerosUno: 'un cero',
        cerosDos: 'dos ceros',
        fraccionesEnunciado: '¿Qué parte está pintada?',
        fraccionesHablar: 'La figura tiene {den} partes iguales. Algunas están pintadas. ¿Qué parte está pintada?',
        fraccionesVisualAria: 'Figura con {den} partes. {num} están pintadas.',
        fraccionAria: '{num} de {den} partes',
        comparaFracEnunciado: '¿Dónde está pintada la parte más grande?',
        comparaFracHablar: 'Mira las dos figuras. ¿Dónde está pintada la parte más grande? Toca esa figura.',
        preciosEnunciado: '¿Cómo se dice este precio?',
        preciosHablar: '{prod} cuesta esto. ¿Cómo se dice este precio?',
        comparaPreciosEnunciado: '¿Qué cuesta más?',
        comparaPreciosHablar: '¿Qué cuesta más? ¿{p1} o {p2}? Mira bien la coma.',
        llegaUnoEnunciado: '¿Te llega el dinero para comprar esto?',
        llegaUnoHablar: 'Tienes {tiene}. {prod} cuesta {precio}. ¿Te llega el dinero?',
        llegaDosEnunciado: '¿Te llega el dinero para comprar los dos?',
        llegaDosHablar: 'Tienes {tiene}. {p1} cuesta {precio1} y {p2} cuesta {precio2}. ¿Te llega el dinero para los dos?',
        etqTienes: 'Tienes:',
        opcionSi: 'Sí, me llega',
        opcionNo: 'No, me falta dinero',
        cambioEnunciado: '¿Cuánto te devuelven?',
        cambioHablar: 'Pagas con un billete de {billete}. Esto cuesta {precio}. ¿Cuánto te devuelven?',
        etqPagas: 'Pagas con:',
        etqCuesta: 'Cuesta:'
      }
    },
    en: {
      title: '🧮 Numbers',
      instruccionMenu: 'Everyday math. Choose an activity.',
      notaMonedero: '💶 To pay with coins, go to {link}.',
      notaMonederoLink: 'The Coin Purse',
      btnVolverMenu: '← Other activities',
      otroNivel: 'Choose another level',
      instruccionExtra: ' First, choose a level.',
      veces: '{n} times',
      resumenFinal: 'You solved {n} questions in {actividad}. Now you have {estrellas} stars.',
      btnMasDificil: 'Do you want to try "{nombre}"?',
      btnOtraActividad: 'Another activity',
      explicacionCorrecta: '✅ Correct! The answer is: ',
      explicacionIncorrectaA: '❌ That is not it. The correct answer is: ',
      pista: '🤔 Try again. Think it through calmly.',
      grupoEtq: { 0: '', 1: 'thousand', 2: 'million', 3: 'billion', 4: 'trillion' },
      leyendaUnidadesTxt: 'ones',
      leyendaDecenasTxt: 'tens',
      leyendaCentenasTxt: 'hundreds',
      leyendaEurosTxt: 'euros',
      leyendaComaTxt: 'the decimal point and cents',
      leyendaPartesPintadasTxt: 'colored parts',
      leyendaPartesTotalTxt: 'total parts',
      euroUno: '1 euro',
      euroVarios: '{e} euros',
      precioConCentimos: '{euros} and {c} cents',
      centenaSingular: 'hundred', centenaPlural: 'hundreds',
      decenaSingular: 'ten', decenaPlural: 'tens',
      unidadSingular: 'one', unidadPlural: 'ones',
      grupo: {
        numeros: 'Numbers',
        calcular: 'Calculate and measure'
      },
      actividad: {
        contar: { nombre: 'Count', detalle: 'Follow the series.', instruccion: 'Look at the numbers. Think what number comes next. Touch that number.' },
        unidades: { nombre: 'Units and tens', detalle: 'What number is it?', instruccion: 'Each color helps you read the number. Blue: ones. Green: tens. Purple: hundreds.' },
        fracciones: { nombre: 'Fractions', detalle: 'The parts of something.', instruccion: 'A fraction is a part of something. Look at the colored parts of the shape.' },
        decimales: { nombre: 'Decimals', detalle: 'Euros and the decimal point.', instruccion: 'The decimal point separates euros and cents. Euros come first. Cents come after.' },
        sumar: { nombre: 'Add', detalle: 'Addition tables.', instruccion: 'Count the colored dots. Touch the answer.' },
        restar: { nombre: 'Subtract', detalle: 'Subtraction tables.', instruccion: 'Subtracting means taking away. Count the dots that do not have a cross.' },
        multiplicar: { nombre: 'Multiply', detalle: 'Multiplication tables.', instruccion: 'Multiplying means adding equal groups. Count the rows of dots.' },
        cabeza: { nombre: 'In your head', detalle: 'Work it out without paper.', instruccion: 'Work out the answer in your head. Notice which digit changes.' },
        llega: { nombre: 'Enough money?', detalle: 'Do you have enough money?', instruccion: 'Look at how much money you have. Look at the price. Think about whether it is enough.' },
        cambio: { nombre: 'The Change', detalle: 'How much change do you get?', instruccion: 'You pay with a bank note. You get back what is left over. Work out how much change you get.' },
        medidas: { nombre: 'Measurements', detalle: 'Meters, kilograms and liters.', instruccion: 'Think about how much each measurement is. Touch the answer.' }
      },
      nivel: {
        c1: 'Counting by 1s', c2: 'Counting by 2s', c5: 'Counting by 5s', c10: 'Counting by 10s',
        u99: 'Up to 99', u999: 'Up to 999', umiles: 'Thousands', umillones: 'Millions and billions', udictado: 'Listen and choose',
        f1: 'Halves and quarters', f2: 'Thirds and sixths', f3: 'Which is bigger?',
        d1: 'Read prices', d2: 'What costs more?',
        s10: 'Sums up to 10', s20: 'Sums up to 20',
        r10: 'Subtraction up to 10', r20: 'Subtraction up to 20',
        m1: 'Times tables 2, 5 and 10', m2: 'Times tables 3 and 4', m3: 'Times tables 6 and 7', m4: 'Times tables 8 and 9',
        k1: 'Doubles', k2: 'Add 10', k3: 'Add 100', k4: 'Add 1,000',
        k5: 'Subtract 10', k6: 'Subtract 100', k7: 'Subtract 1,000',
        k8: 'Multiply x10', k9: 'Multiply x100',
        ll1: 'One item', ll2: 'Two items',
        ca1: 'Easy change', ca2: 'Change with cents',
        me1: 'Length: meters', me2: 'Weight: kilograms', me3: 'Capacity: liters'
      },
      producto: {
        pan: 'the bread', leche: 'the milk', zumo: 'the juice', manzanas: 'the apples',
        queso: 'the cheese', galletas: 'the cookies', lapiz: 'the pencil', cuaderno: 'the notebook'
      },
      gen: {
        contarEnunciado: 'What number comes next?',
        contarHablar: 'Count by {paso}s. {seq}. What number comes next?',
        bloquesEnunciado: 'What number do the blocks make?',
        bloquesHablar: 'What number do the blocks make? There are {texto}.',
        bloquesVisualAria: 'Blocks: {texto}',
        lecturaEnunciadoNumASim: 'How do you read this number?',
        lecturaHablarNumASim: 'How do you read this number? The labels below help you.',
        lecturaEnunciadoSimANum: 'What number is it?',
        lecturaHablarSimANum: '{palabras}. What number is it?',
        dictadoEnunciado: 'Listen to the number. Then touch it.',
        dictadoVisualAria: 'Listen to the number with the audio button.',
        sumarEnunciado: 'How much is {a} + {b}?',
        sumarHablar: 'How much is {a} plus {b}? Count the dots.',
        restarEnunciado: 'How much is {a} − {b}?',
        restarHablar: 'How much is {a} minus {b}? Count the dots that do not have a cross.',
        restarPista: 'Take away {b}. Count the dots left.',
        multiplicarEnunciado: 'How much is {a} × {b}?',
        multiplicarHablar: 'How much is {a} times {b}? Look: {a} rows with {b} dots each.',
        multiplicarPista: '{a} rows. Each row has {b} dots.',
        doblesEnunciado: 'How much is {a} + {a}?',
        doblesHablar: 'How much is {a} plus {a}? Both numbers are the same. It is a double.',
        doblesPista: 'Both numbers are the same. It is a double.',
        pistaDecenas: 'Only the green digit changes: the tens.',
        pistaCentenas: 'Only the purple digit changes: the hundreds.',
        pistaMiles: 'Only the thousands digit changes.',
        sumaGrandeEnunciado: 'How much is {n} + {suma}?',
        sumaGrandeHablar: 'How much is {n} plus {suma}? {pista}',
        restaGrandeEnunciado: 'How much is {n} − {resta}?',
        restaGrandeHablar: 'How much is {n} minus {resta}? {pista}',
        multiplicaGrandeEnunciado: 'How much is {n} × {factor}?',
        multiplicaGrandeHablar: 'How much is {n} times {factor}? Add {ceros} at the end.',
        multiplicaGrandePista: 'Add {ceros} at the end of {n}.',
        cerosUno: 'one zero',
        cerosDos: 'two zeros',
        fraccionesEnunciado: 'What part is colored?',
        fraccionesHablar: 'The shape has {den} equal parts. Some are colored. What part is colored?',
        fraccionesVisualAria: 'Shape with {den} parts. {num} are colored.',
        fraccionAria: '{num} of {den} parts',
        comparaFracEnunciado: 'Where is the bigger part colored?',
        comparaFracHablar: 'Look at the two shapes. Where is the bigger part colored? Touch that shape.',
        preciosEnunciado: 'How do you say this price?',
        preciosHablar: '{prod} costs this. How do you say this price?',
        comparaPreciosEnunciado: 'What costs more?',
        comparaPreciosHablar: 'What costs more? {p1} or {p2}? Look carefully at the decimal point.',
        llegaUnoEnunciado: 'Is that enough money to buy this?',
        llegaUnoHablar: 'You have {tiene}. {prod} costs {precio}. Is that enough money?',
        llegaDosEnunciado: 'Is that enough money to buy both?',
        llegaDosHablar: 'You have {tiene}. {p1} costs {precio1} and {p2} costs {precio2}. Is that enough money for both?',
        etqTienes: 'You have:',
        opcionSi: 'Yes, that is enough',
        opcionNo: 'No, I do not have enough',
        cambioEnunciado: 'How much change do you get?',
        cambioHablar: 'You pay with a {billete} note. This costs {precio}. How much change do you get?',
        etqPagas: 'You pay with:',
        etqCuesta: 'Costs:'
      }
    }
  });
})();
